// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/go-park-mail-ru/2025_1_Quza/auth/internal/repository.AccessPolicies -o access_policies_minimock.go -n AccessPoliciesMock -p mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// AccessPoliciesMock implements mm_repository.AccessPolicies
type AccessPoliciesMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCheck          func(path string, role string) (err error)
	funcCheckOrigin    string
	inspectFuncCheck   func(path string, role string)
	afterCheckCounter  uint64
	beforeCheckCounter uint64
	CheckMock          mAccessPoliciesMockCheck
}

// NewAccessPoliciesMock returns a mock for mm_repository.AccessPolicies
func NewAccessPoliciesMock(t minimock.Tester) *AccessPoliciesMock {
	m := &AccessPoliciesMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CheckMock = mAccessPoliciesMockCheck{mock: m}
	m.CheckMock.callArgs = []*AccessPoliciesMockCheckParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAccessPoliciesMockCheck struct {
	optional           bool
	mock               *AccessPoliciesMock
	defaultExpectation *AccessPoliciesMockCheckExpectation
	expectations       []*AccessPoliciesMockCheckExpectation

	callArgs []*AccessPoliciesMockCheckParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AccessPoliciesMockCheckExpectation specifies expectation struct of the AccessPolicies.Check
type AccessPoliciesMockCheckExpectation struct {
	mock               *AccessPoliciesMock
	params             *AccessPoliciesMockCheckParams
	paramPtrs          *AccessPoliciesMockCheckParamPtrs
	expectationOrigins AccessPoliciesMockCheckExpectationOrigins
	results            *AccessPoliciesMockCheckResults
	returnOrigin       string
	Counter            uint64
}

// AccessPoliciesMockCheckParams contains parameters of the AccessPolicies.Check
type AccessPoliciesMockCheckParams struct {
	path string
	role string
}

// AccessPoliciesMockCheckParamPtrs contains pointers to parameters of the AccessPolicies.Check
type AccessPoliciesMockCheckParamPtrs struct {
	path *string
	role *string
}

// AccessPoliciesMockCheckResults contains results of the AccessPolicies.Check
type AccessPoliciesMockCheckResults struct {
	err error
}

// AccessPoliciesMockCheckOrigins contains origins of expectations of the AccessPolicies.Check
type AccessPoliciesMockCheckExpectationOrigins struct {
	origin     string
	originPath string
	originRole string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCheck *mAccessPoliciesMockCheck) Optional() *mAccessPoliciesMockCheck {
	mmCheck.optional = true
	return mmCheck
}

// Expect sets up expected params for AccessPolicies.Check
func (mmCheck *mAccessPoliciesMockCheck) Expect(path string, role string) *mAccessPoliciesMockCheck {
	if mmCheck.mock.funcCheck != nil {
		mmCheck.mock.t.Fatalf("AccessPoliciesMock.Check mock is already set by Set")
	}

	if mmCheck.defaultExpectation == nil {
		mmCheck.defaultExpectation = &AccessPoliciesMockCheckExpectation{}
	}

	if mmCheck.defaultExpectation.paramPtrs != nil {
		mmCheck.mock.t.Fatalf("AccessPoliciesMock.Check mock is already set by ExpectParams functions")
	}

	mmCheck.defaultExpectation.params = &AccessPoliciesMockCheckParams{path, role}
	mmCheck.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCheck.expectations {
		if minimock.Equal(e.params, mmCheck.defaultExpectation.params) {
			mmCheck.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCheck.defaultExpectation.params)
		}
	}

	return mmCheck
}

// ExpectPathParam1 sets up expected param path for AccessPolicies.Check
func (mmCheck *mAccessPoliciesMockCheck) ExpectPathParam1(path string) *mAccessPoliciesMockCheck {
	if mmCheck.mock.funcCheck != nil {
		mmCheck.mock.t.Fatalf("AccessPoliciesMock.Check mock is already set by Set")
	}

	if mmCheck.defaultExpectation == nil {
		mmCheck.defaultExpectation = &AccessPoliciesMockCheckExpectation{}
	}

	if mmCheck.defaultExpectation.params != nil {
		mmCheck.mock.t.Fatalf("AccessPoliciesMock.Check mock is already set by Expect")
	}

	if mmCheck.defaultExpectation.paramPtrs == nil {
		mmCheck.defaultExpectation.paramPtrs = &AccessPoliciesMockCheckParamPtrs{}
	}
	mmCheck.defaultExpectation.paramPtrs.path = &path
	mmCheck.defaultExpectation.expectationOrigins.originPath = minimock.CallerInfo(1)

	return mmCheck
}

// ExpectRoleParam2 sets up expected param role for AccessPolicies.Check
func (mmCheck *mAccessPoliciesMockCheck) ExpectRoleParam2(role string) *mAccessPoliciesMockCheck {
	if mmCheck.mock.funcCheck != nil {
		mmCheck.mock.t.Fatalf("AccessPoliciesMock.Check mock is already set by Set")
	}

	if mmCheck.defaultExpectation == nil {
		mmCheck.defaultExpectation = &AccessPoliciesMockCheckExpectation{}
	}

	if mmCheck.defaultExpectation.params != nil {
		mmCheck.mock.t.Fatalf("AccessPoliciesMock.Check mock is already set by Expect")
	}

	if mmCheck.defaultExpectation.paramPtrs == nil {
		mmCheck.defaultExpectation.paramPtrs = &AccessPoliciesMockCheckParamPtrs{}
	}
	mmCheck.defaultExpectation.paramPtrs.role = &role
	mmCheck.defaultExpectation.expectationOrigins.originRole = minimock.CallerInfo(1)

	return mmCheck
}

// Inspect accepts an inspector function that has same arguments as the AccessPolicies.Check
func (mmCheck *mAccessPoliciesMockCheck) Inspect(f func(path string, role string)) *mAccessPoliciesMockCheck {
	if mmCheck.mock.inspectFuncCheck != nil {
		mmCheck.mock.t.Fatalf("Inspect function is already set for AccessPoliciesMock.Check")
	}

	mmCheck.mock.inspectFuncCheck = f

	return mmCheck
}

// Return sets up results that will be returned by AccessPolicies.Check
func (mmCheck *mAccessPoliciesMockCheck) Return(err error) *AccessPoliciesMock {
	if mmCheck.mock.funcCheck != nil {
		mmCheck.mock.t.Fatalf("AccessPoliciesMock.Check mock is already set by Set")
	}

	if mmCheck.defaultExpectation == nil {
		mmCheck.defaultExpectation = &AccessPoliciesMockCheckExpectation{mock: mmCheck.mock}
	}
	mmCheck.defaultExpectation.results = &AccessPoliciesMockCheckResults{err}
	mmCheck.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCheck.mock
}

// Set uses given function f to mock the AccessPolicies.Check method
func (mmCheck *mAccessPoliciesMockCheck) Set(f func(path string, role string) (err error)) *AccessPoliciesMock {
	if mmCheck.defaultExpectation != nil {
		mmCheck.mock.t.Fatalf("Default expectation is already set for the AccessPolicies.Check method")
	}

	if len(mmCheck.expectations) > 0 {
		mmCheck.mock.t.Fatalf("Some expectations are already set for the AccessPolicies.Check method")
	}

	mmCheck.mock.funcCheck = f
	mmCheck.mock.funcCheckOrigin = minimock.CallerInfo(1)
	return mmCheck.mock
}

// When sets expectation for the AccessPolicies.Check which will trigger the result defined by the following
// Then helper
func (mmCheck *mAccessPoliciesMockCheck) When(path string, role string) *AccessPoliciesMockCheckExpectation {
	if mmCheck.mock.funcCheck != nil {
		mmCheck.mock.t.Fatalf("AccessPoliciesMock.Check mock is already set by Set")
	}

	expectation := &AccessPoliciesMockCheckExpectation{
		mock:               mmCheck.mock,
		params:             &AccessPoliciesMockCheckParams{path, role},
		expectationOrigins: AccessPoliciesMockCheckExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCheck.expectations = append(mmCheck.expectations, expectation)
	return expectation
}

// Then sets up AccessPolicies.Check return parameters for the expectation previously defined by the When method
func (e *AccessPoliciesMockCheckExpectation) Then(err error) *AccessPoliciesMock {
	e.results = &AccessPoliciesMockCheckResults{err}
	return e.mock
}

// Times sets number of times AccessPolicies.Check should be invoked
func (mmCheck *mAccessPoliciesMockCheck) Times(n uint64) *mAccessPoliciesMockCheck {
	if n == 0 {
		mmCheck.mock.t.Fatalf("Times of AccessPoliciesMock.Check mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCheck.expectedInvocations, n)
	mmCheck.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCheck
}

func (mmCheck *mAccessPoliciesMockCheck) invocationsDone() bool {
	if len(mmCheck.expectations) == 0 && mmCheck.defaultExpectation == nil && mmCheck.mock.funcCheck == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCheck.mock.afterCheckCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCheck.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Check implements mm_repository.AccessPolicies
func (mmCheck *AccessPoliciesMock) Check(path string, role string) (err error) {
	mm_atomic.AddUint64(&mmCheck.beforeCheckCounter, 1)
	defer mm_atomic.AddUint64(&mmCheck.afterCheckCounter, 1)

	mmCheck.t.Helper()

	if mmCheck.inspectFuncCheck != nil {
		mmCheck.inspectFuncCheck(path, role)
	}

	mm_params := AccessPoliciesMockCheckParams{path, role}

	// Record call args
	mmCheck.CheckMock.mutex.Lock()
	mmCheck.CheckMock.callArgs = append(mmCheck.CheckMock.callArgs, &mm_params)
	mmCheck.CheckMock.mutex.Unlock()

	for _, e := range mmCheck.CheckMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmCheck.CheckMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCheck.CheckMock.defaultExpectation.Counter, 1)
		mm_want := mmCheck.CheckMock.defaultExpectation.params
		mm_want_ptrs := mmCheck.CheckMock.defaultExpectation.paramPtrs

		mm_got := AccessPoliciesMockCheckParams{path, role}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.path != nil && !minimock.Equal(*mm_want_ptrs.path, mm_got.path) {
				mmCheck.t.Errorf("AccessPoliciesMock.Check got unexpected parameter path, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCheck.CheckMock.defaultExpectation.expectationOrigins.originPath, *mm_want_ptrs.path, mm_got.path, minimock.Diff(*mm_want_ptrs.path, mm_got.path))
			}

			if mm_want_ptrs.role != nil && !minimock.Equal(*mm_want_ptrs.role, mm_got.role) {
				mmCheck.t.Errorf("AccessPoliciesMock.Check got unexpected parameter role, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCheck.CheckMock.defaultExpectation.expectationOrigins.originRole, *mm_want_ptrs.role, mm_got.role, minimock.Diff(*mm_want_ptrs.role, mm_got.role))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCheck.t.Errorf("AccessPoliciesMock.Check got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCheck.CheckMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCheck.CheckMock.defaultExpectation.results
		if mm_results == nil {
			mmCheck.t.Fatal("No results are set for the AccessPoliciesMock.Check")
		}
		return (*mm_results).err
	}
	if mmCheck.funcCheck != nil {
		return mmCheck.funcCheck(path, role)
	}
	mmCheck.t.Fatalf("Unexpected call to AccessPoliciesMock.Check. %v %v", path, role)
	return
}

// CheckAfterCounter returns a count of finished AccessPoliciesMock.Check invocations
func (mmCheck *AccessPoliciesMock) CheckAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCheck.afterCheckCounter)
}

// CheckBeforeCounter returns a count of AccessPoliciesMock.Check invocations
func (mmCheck *AccessPoliciesMock) CheckBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCheck.beforeCheckCounter)
}

// Calls returns a list of arguments used in each call to AccessPoliciesMock.Check.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCheck *mAccessPoliciesMockCheck) Calls() []*AccessPoliciesMockCheckParams {
	mmCheck.mutex.RLock()

	argCopy := make([]*AccessPoliciesMockCheckParams, len(mmCheck.callArgs))
	copy(argCopy, mmCheck.callArgs)

	mmCheck.mutex.RUnlock()

	return argCopy
}

// MinimockCheckDone returns true if the count of the Check invocations corresponds
// the number of defined expectations
func (m *AccessPoliciesMock) MinimockCheckDone() bool {
	if m.CheckMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CheckMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CheckMock.invocationsDone()
}

// MinimockCheckInspect logs each unmet expectation
func (m *AccessPoliciesMock) MinimockCheckInspect() {
	for _, e := range m.CheckMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AccessPoliciesMock.Check at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCheckCounter := mm_atomic.LoadUint64(&m.afterCheckCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CheckMock.defaultExpectation != nil && afterCheckCounter < 1 {
		if m.CheckMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AccessPoliciesMock.Check at\n%s", m.CheckMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AccessPoliciesMock.Check at\n%s with params: %#v", m.CheckMock.defaultExpectation.expectationOrigins.origin, *m.CheckMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCheck != nil && afterCheckCounter < 1 {
		m.t.Errorf("Expected call to AccessPoliciesMock.Check at\n%s", m.funcCheckOrigin)
	}

	if !m.CheckMock.invocationsDone() && afterCheckCounter > 0 {
		m.t.Errorf("Expected %d calls to AccessPoliciesMock.Check at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CheckMock.expectedInvocations), m.CheckMock.expectedInvocationsOrigin, afterCheckCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AccessPoliciesMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCheckInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AccessPoliciesMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AccessPoliciesMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCheckDone()
}
