// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/go-park-mail-ru/2025_1_Quza/auth/internal/repository.UserRepositoryInterface -o user_repository_interface_minimock.go -n UserRepositoryInterfaceMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/go-park-mail-ru/2025_1_Quza/auth/internal/model"
	"github.com/gojuno/minimock/v3"
)

// UserRepositoryInterfaceMock implements mm_repository.UserRepositoryInterface
type UserRepositoryInterfaceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcDelete          func(ctx context.Context, id int) (err error)
	funcDeleteOrigin    string
	inspectFuncDelete   func(ctx context.Context, id int)
	afterDeleteCounter  uint64
	beforeDeleteCounter uint64
	DeleteMock          mUserRepositoryInterfaceMockDelete

	funcGetUserById          func(ctx context.Context, id int) (up1 *model.User, err error)
	funcGetUserByIdOrigin    string
	inspectFuncGetUserById   func(ctx context.Context, id int)
	afterGetUserByIdCounter  uint64
	beforeGetUserByIdCounter uint64
	GetUserByIdMock          mUserRepositoryInterfaceMockGetUserById

	funcGetUserByName          func(ctx context.Context, name string) (up1 *model.User, err error)
	funcGetUserByNameOrigin    string
	inspectFuncGetUserByName   func(ctx context.Context, name string)
	afterGetUserByNameCounter  uint64
	beforeGetUserByNameCounter uint64
	GetUserByNameMock          mUserRepositoryInterfaceMockGetUserByName

	funcSave          func(ctx context.Context, user model.User) (i1 int, err error)
	funcSaveOrigin    string
	inspectFuncSave   func(ctx context.Context, user model.User)
	afterSaveCounter  uint64
	beforeSaveCounter uint64
	SaveMock          mUserRepositoryInterfaceMockSave

	funcUpdate          func(ctx context.Context, update model.User) (err error)
	funcUpdateOrigin    string
	inspectFuncUpdate   func(ctx context.Context, update model.User)
	afterUpdateCounter  uint64
	beforeUpdateCounter uint64
	UpdateMock          mUserRepositoryInterfaceMockUpdate
}

// NewUserRepositoryInterfaceMock returns a mock for mm_repository.UserRepositoryInterface
func NewUserRepositoryInterfaceMock(t minimock.Tester) *UserRepositoryInterfaceMock {
	m := &UserRepositoryInterfaceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DeleteMock = mUserRepositoryInterfaceMockDelete{mock: m}
	m.DeleteMock.callArgs = []*UserRepositoryInterfaceMockDeleteParams{}

	m.GetUserByIdMock = mUserRepositoryInterfaceMockGetUserById{mock: m}
	m.GetUserByIdMock.callArgs = []*UserRepositoryInterfaceMockGetUserByIdParams{}

	m.GetUserByNameMock = mUserRepositoryInterfaceMockGetUserByName{mock: m}
	m.GetUserByNameMock.callArgs = []*UserRepositoryInterfaceMockGetUserByNameParams{}

	m.SaveMock = mUserRepositoryInterfaceMockSave{mock: m}
	m.SaveMock.callArgs = []*UserRepositoryInterfaceMockSaveParams{}

	m.UpdateMock = mUserRepositoryInterfaceMockUpdate{mock: m}
	m.UpdateMock.callArgs = []*UserRepositoryInterfaceMockUpdateParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUserRepositoryInterfaceMockDelete struct {
	optional           bool
	mock               *UserRepositoryInterfaceMock
	defaultExpectation *UserRepositoryInterfaceMockDeleteExpectation
	expectations       []*UserRepositoryInterfaceMockDeleteExpectation

	callArgs []*UserRepositoryInterfaceMockDeleteParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserRepositoryInterfaceMockDeleteExpectation specifies expectation struct of the UserRepositoryInterface.Delete
type UserRepositoryInterfaceMockDeleteExpectation struct {
	mock               *UserRepositoryInterfaceMock
	params             *UserRepositoryInterfaceMockDeleteParams
	paramPtrs          *UserRepositoryInterfaceMockDeleteParamPtrs
	expectationOrigins UserRepositoryInterfaceMockDeleteExpectationOrigins
	results            *UserRepositoryInterfaceMockDeleteResults
	returnOrigin       string
	Counter            uint64
}

// UserRepositoryInterfaceMockDeleteParams contains parameters of the UserRepositoryInterface.Delete
type UserRepositoryInterfaceMockDeleteParams struct {
	ctx context.Context
	id  int
}

// UserRepositoryInterfaceMockDeleteParamPtrs contains pointers to parameters of the UserRepositoryInterface.Delete
type UserRepositoryInterfaceMockDeleteParamPtrs struct {
	ctx *context.Context
	id  *int
}

// UserRepositoryInterfaceMockDeleteResults contains results of the UserRepositoryInterface.Delete
type UserRepositoryInterfaceMockDeleteResults struct {
	err error
}

// UserRepositoryInterfaceMockDeleteOrigins contains origins of expectations of the UserRepositoryInterface.Delete
type UserRepositoryInterfaceMockDeleteExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDelete *mUserRepositoryInterfaceMockDelete) Optional() *mUserRepositoryInterfaceMockDelete {
	mmDelete.optional = true
	return mmDelete
}

// Expect sets up expected params for UserRepositoryInterface.Delete
func (mmDelete *mUserRepositoryInterfaceMockDelete) Expect(ctx context.Context, id int) *mUserRepositoryInterfaceMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("UserRepositoryInterfaceMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &UserRepositoryInterfaceMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.paramPtrs != nil {
		mmDelete.mock.t.Fatalf("UserRepositoryInterfaceMock.Delete mock is already set by ExpectParams functions")
	}

	mmDelete.defaultExpectation.params = &UserRepositoryInterfaceMockDeleteParams{ctx, id}
	mmDelete.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDelete.expectations {
		if minimock.Equal(e.params, mmDelete.defaultExpectation.params) {
			mmDelete.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDelete.defaultExpectation.params)
		}
	}

	return mmDelete
}

// ExpectCtxParam1 sets up expected param ctx for UserRepositoryInterface.Delete
func (mmDelete *mUserRepositoryInterfaceMockDelete) ExpectCtxParam1(ctx context.Context) *mUserRepositoryInterfaceMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("UserRepositoryInterfaceMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &UserRepositoryInterfaceMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("UserRepositoryInterfaceMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &UserRepositoryInterfaceMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.ctx = &ctx
	mmDelete.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDelete
}

// ExpectIdParam2 sets up expected param id for UserRepositoryInterface.Delete
func (mmDelete *mUserRepositoryInterfaceMockDelete) ExpectIdParam2(id int) *mUserRepositoryInterfaceMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("UserRepositoryInterfaceMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &UserRepositoryInterfaceMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("UserRepositoryInterfaceMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &UserRepositoryInterfaceMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.id = &id
	mmDelete.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmDelete
}

// Inspect accepts an inspector function that has same arguments as the UserRepositoryInterface.Delete
func (mmDelete *mUserRepositoryInterfaceMockDelete) Inspect(f func(ctx context.Context, id int)) *mUserRepositoryInterfaceMockDelete {
	if mmDelete.mock.inspectFuncDelete != nil {
		mmDelete.mock.t.Fatalf("Inspect function is already set for UserRepositoryInterfaceMock.Delete")
	}

	mmDelete.mock.inspectFuncDelete = f

	return mmDelete
}

// Return sets up results that will be returned by UserRepositoryInterface.Delete
func (mmDelete *mUserRepositoryInterfaceMockDelete) Return(err error) *UserRepositoryInterfaceMock {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("UserRepositoryInterfaceMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &UserRepositoryInterfaceMockDeleteExpectation{mock: mmDelete.mock}
	}
	mmDelete.defaultExpectation.results = &UserRepositoryInterfaceMockDeleteResults{err}
	mmDelete.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// Set uses given function f to mock the UserRepositoryInterface.Delete method
func (mmDelete *mUserRepositoryInterfaceMockDelete) Set(f func(ctx context.Context, id int) (err error)) *UserRepositoryInterfaceMock {
	if mmDelete.defaultExpectation != nil {
		mmDelete.mock.t.Fatalf("Default expectation is already set for the UserRepositoryInterface.Delete method")
	}

	if len(mmDelete.expectations) > 0 {
		mmDelete.mock.t.Fatalf("Some expectations are already set for the UserRepositoryInterface.Delete method")
	}

	mmDelete.mock.funcDelete = f
	mmDelete.mock.funcDeleteOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// When sets expectation for the UserRepositoryInterface.Delete which will trigger the result defined by the following
// Then helper
func (mmDelete *mUserRepositoryInterfaceMockDelete) When(ctx context.Context, id int) *UserRepositoryInterfaceMockDeleteExpectation {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("UserRepositoryInterfaceMock.Delete mock is already set by Set")
	}

	expectation := &UserRepositoryInterfaceMockDeleteExpectation{
		mock:               mmDelete.mock,
		params:             &UserRepositoryInterfaceMockDeleteParams{ctx, id},
		expectationOrigins: UserRepositoryInterfaceMockDeleteExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDelete.expectations = append(mmDelete.expectations, expectation)
	return expectation
}

// Then sets up UserRepositoryInterface.Delete return parameters for the expectation previously defined by the When method
func (e *UserRepositoryInterfaceMockDeleteExpectation) Then(err error) *UserRepositoryInterfaceMock {
	e.results = &UserRepositoryInterfaceMockDeleteResults{err}
	return e.mock
}

// Times sets number of times UserRepositoryInterface.Delete should be invoked
func (mmDelete *mUserRepositoryInterfaceMockDelete) Times(n uint64) *mUserRepositoryInterfaceMockDelete {
	if n == 0 {
		mmDelete.mock.t.Fatalf("Times of UserRepositoryInterfaceMock.Delete mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDelete.expectedInvocations, n)
	mmDelete.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDelete
}

func (mmDelete *mUserRepositoryInterfaceMockDelete) invocationsDone() bool {
	if len(mmDelete.expectations) == 0 && mmDelete.defaultExpectation == nil && mmDelete.mock.funcDelete == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDelete.mock.afterDeleteCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDelete.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Delete implements mm_repository.UserRepositoryInterface
func (mmDelete *UserRepositoryInterfaceMock) Delete(ctx context.Context, id int) (err error) {
	mm_atomic.AddUint64(&mmDelete.beforeDeleteCounter, 1)
	defer mm_atomic.AddUint64(&mmDelete.afterDeleteCounter, 1)

	mmDelete.t.Helper()

	if mmDelete.inspectFuncDelete != nil {
		mmDelete.inspectFuncDelete(ctx, id)
	}

	mm_params := UserRepositoryInterfaceMockDeleteParams{ctx, id}

	// Record call args
	mmDelete.DeleteMock.mutex.Lock()
	mmDelete.DeleteMock.callArgs = append(mmDelete.DeleteMock.callArgs, &mm_params)
	mmDelete.DeleteMock.mutex.Unlock()

	for _, e := range mmDelete.DeleteMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDelete.DeleteMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDelete.DeleteMock.defaultExpectation.Counter, 1)
		mm_want := mmDelete.DeleteMock.defaultExpectation.params
		mm_want_ptrs := mmDelete.DeleteMock.defaultExpectation.paramPtrs

		mm_got := UserRepositoryInterfaceMockDeleteParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDelete.t.Errorf("UserRepositoryInterfaceMock.Delete got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmDelete.t.Errorf("UserRepositoryInterfaceMock.Delete got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDelete.t.Errorf("UserRepositoryInterfaceMock.Delete got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDelete.DeleteMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDelete.DeleteMock.defaultExpectation.results
		if mm_results == nil {
			mmDelete.t.Fatal("No results are set for the UserRepositoryInterfaceMock.Delete")
		}
		return (*mm_results).err
	}
	if mmDelete.funcDelete != nil {
		return mmDelete.funcDelete(ctx, id)
	}
	mmDelete.t.Fatalf("Unexpected call to UserRepositoryInterfaceMock.Delete. %v %v", ctx, id)
	return
}

// DeleteAfterCounter returns a count of finished UserRepositoryInterfaceMock.Delete invocations
func (mmDelete *UserRepositoryInterfaceMock) DeleteAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.afterDeleteCounter)
}

// DeleteBeforeCounter returns a count of UserRepositoryInterfaceMock.Delete invocations
func (mmDelete *UserRepositoryInterfaceMock) DeleteBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.beforeDeleteCounter)
}

// Calls returns a list of arguments used in each call to UserRepositoryInterfaceMock.Delete.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDelete *mUserRepositoryInterfaceMockDelete) Calls() []*UserRepositoryInterfaceMockDeleteParams {
	mmDelete.mutex.RLock()

	argCopy := make([]*UserRepositoryInterfaceMockDeleteParams, len(mmDelete.callArgs))
	copy(argCopy, mmDelete.callArgs)

	mmDelete.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteDone returns true if the count of the Delete invocations corresponds
// the number of defined expectations
func (m *UserRepositoryInterfaceMock) MinimockDeleteDone() bool {
	if m.DeleteMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteMock.invocationsDone()
}

// MinimockDeleteInspect logs each unmet expectation
func (m *UserRepositoryInterfaceMock) MinimockDeleteInspect() {
	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserRepositoryInterfaceMock.Delete at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteCounter := mm_atomic.LoadUint64(&m.afterDeleteCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteMock.defaultExpectation != nil && afterDeleteCounter < 1 {
		if m.DeleteMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserRepositoryInterfaceMock.Delete at\n%s", m.DeleteMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserRepositoryInterfaceMock.Delete at\n%s with params: %#v", m.DeleteMock.defaultExpectation.expectationOrigins.origin, *m.DeleteMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDelete != nil && afterDeleteCounter < 1 {
		m.t.Errorf("Expected call to UserRepositoryInterfaceMock.Delete at\n%s", m.funcDeleteOrigin)
	}

	if !m.DeleteMock.invocationsDone() && afterDeleteCounter > 0 {
		m.t.Errorf("Expected %d calls to UserRepositoryInterfaceMock.Delete at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteMock.expectedInvocations), m.DeleteMock.expectedInvocationsOrigin, afterDeleteCounter)
	}
}

type mUserRepositoryInterfaceMockGetUserById struct {
	optional           bool
	mock               *UserRepositoryInterfaceMock
	defaultExpectation *UserRepositoryInterfaceMockGetUserByIdExpectation
	expectations       []*UserRepositoryInterfaceMockGetUserByIdExpectation

	callArgs []*UserRepositoryInterfaceMockGetUserByIdParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserRepositoryInterfaceMockGetUserByIdExpectation specifies expectation struct of the UserRepositoryInterface.GetUserById
type UserRepositoryInterfaceMockGetUserByIdExpectation struct {
	mock               *UserRepositoryInterfaceMock
	params             *UserRepositoryInterfaceMockGetUserByIdParams
	paramPtrs          *UserRepositoryInterfaceMockGetUserByIdParamPtrs
	expectationOrigins UserRepositoryInterfaceMockGetUserByIdExpectationOrigins
	results            *UserRepositoryInterfaceMockGetUserByIdResults
	returnOrigin       string
	Counter            uint64
}

// UserRepositoryInterfaceMockGetUserByIdParams contains parameters of the UserRepositoryInterface.GetUserById
type UserRepositoryInterfaceMockGetUserByIdParams struct {
	ctx context.Context
	id  int
}

// UserRepositoryInterfaceMockGetUserByIdParamPtrs contains pointers to parameters of the UserRepositoryInterface.GetUserById
type UserRepositoryInterfaceMockGetUserByIdParamPtrs struct {
	ctx *context.Context
	id  *int
}

// UserRepositoryInterfaceMockGetUserByIdResults contains results of the UserRepositoryInterface.GetUserById
type UserRepositoryInterfaceMockGetUserByIdResults struct {
	up1 *model.User
	err error
}

// UserRepositoryInterfaceMockGetUserByIdOrigins contains origins of expectations of the UserRepositoryInterface.GetUserById
type UserRepositoryInterfaceMockGetUserByIdExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetUserById *mUserRepositoryInterfaceMockGetUserById) Optional() *mUserRepositoryInterfaceMockGetUserById {
	mmGetUserById.optional = true
	return mmGetUserById
}

// Expect sets up expected params for UserRepositoryInterface.GetUserById
func (mmGetUserById *mUserRepositoryInterfaceMockGetUserById) Expect(ctx context.Context, id int) *mUserRepositoryInterfaceMockGetUserById {
	if mmGetUserById.mock.funcGetUserById != nil {
		mmGetUserById.mock.t.Fatalf("UserRepositoryInterfaceMock.GetUserById mock is already set by Set")
	}

	if mmGetUserById.defaultExpectation == nil {
		mmGetUserById.defaultExpectation = &UserRepositoryInterfaceMockGetUserByIdExpectation{}
	}

	if mmGetUserById.defaultExpectation.paramPtrs != nil {
		mmGetUserById.mock.t.Fatalf("UserRepositoryInterfaceMock.GetUserById mock is already set by ExpectParams functions")
	}

	mmGetUserById.defaultExpectation.params = &UserRepositoryInterfaceMockGetUserByIdParams{ctx, id}
	mmGetUserById.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetUserById.expectations {
		if minimock.Equal(e.params, mmGetUserById.defaultExpectation.params) {
			mmGetUserById.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetUserById.defaultExpectation.params)
		}
	}

	return mmGetUserById
}

// ExpectCtxParam1 sets up expected param ctx for UserRepositoryInterface.GetUserById
func (mmGetUserById *mUserRepositoryInterfaceMockGetUserById) ExpectCtxParam1(ctx context.Context) *mUserRepositoryInterfaceMockGetUserById {
	if mmGetUserById.mock.funcGetUserById != nil {
		mmGetUserById.mock.t.Fatalf("UserRepositoryInterfaceMock.GetUserById mock is already set by Set")
	}

	if mmGetUserById.defaultExpectation == nil {
		mmGetUserById.defaultExpectation = &UserRepositoryInterfaceMockGetUserByIdExpectation{}
	}

	if mmGetUserById.defaultExpectation.params != nil {
		mmGetUserById.mock.t.Fatalf("UserRepositoryInterfaceMock.GetUserById mock is already set by Expect")
	}

	if mmGetUserById.defaultExpectation.paramPtrs == nil {
		mmGetUserById.defaultExpectation.paramPtrs = &UserRepositoryInterfaceMockGetUserByIdParamPtrs{}
	}
	mmGetUserById.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetUserById.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetUserById
}

// ExpectIdParam2 sets up expected param id for UserRepositoryInterface.GetUserById
func (mmGetUserById *mUserRepositoryInterfaceMockGetUserById) ExpectIdParam2(id int) *mUserRepositoryInterfaceMockGetUserById {
	if mmGetUserById.mock.funcGetUserById != nil {
		mmGetUserById.mock.t.Fatalf("UserRepositoryInterfaceMock.GetUserById mock is already set by Set")
	}

	if mmGetUserById.defaultExpectation == nil {
		mmGetUserById.defaultExpectation = &UserRepositoryInterfaceMockGetUserByIdExpectation{}
	}

	if mmGetUserById.defaultExpectation.params != nil {
		mmGetUserById.mock.t.Fatalf("UserRepositoryInterfaceMock.GetUserById mock is already set by Expect")
	}

	if mmGetUserById.defaultExpectation.paramPtrs == nil {
		mmGetUserById.defaultExpectation.paramPtrs = &UserRepositoryInterfaceMockGetUserByIdParamPtrs{}
	}
	mmGetUserById.defaultExpectation.paramPtrs.id = &id
	mmGetUserById.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmGetUserById
}

// Inspect accepts an inspector function that has same arguments as the UserRepositoryInterface.GetUserById
func (mmGetUserById *mUserRepositoryInterfaceMockGetUserById) Inspect(f func(ctx context.Context, id int)) *mUserRepositoryInterfaceMockGetUserById {
	if mmGetUserById.mock.inspectFuncGetUserById != nil {
		mmGetUserById.mock.t.Fatalf("Inspect function is already set for UserRepositoryInterfaceMock.GetUserById")
	}

	mmGetUserById.mock.inspectFuncGetUserById = f

	return mmGetUserById
}

// Return sets up results that will be returned by UserRepositoryInterface.GetUserById
func (mmGetUserById *mUserRepositoryInterfaceMockGetUserById) Return(up1 *model.User, err error) *UserRepositoryInterfaceMock {
	if mmGetUserById.mock.funcGetUserById != nil {
		mmGetUserById.mock.t.Fatalf("UserRepositoryInterfaceMock.GetUserById mock is already set by Set")
	}

	if mmGetUserById.defaultExpectation == nil {
		mmGetUserById.defaultExpectation = &UserRepositoryInterfaceMockGetUserByIdExpectation{mock: mmGetUserById.mock}
	}
	mmGetUserById.defaultExpectation.results = &UserRepositoryInterfaceMockGetUserByIdResults{up1, err}
	mmGetUserById.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetUserById.mock
}

// Set uses given function f to mock the UserRepositoryInterface.GetUserById method
func (mmGetUserById *mUserRepositoryInterfaceMockGetUserById) Set(f func(ctx context.Context, id int) (up1 *model.User, err error)) *UserRepositoryInterfaceMock {
	if mmGetUserById.defaultExpectation != nil {
		mmGetUserById.mock.t.Fatalf("Default expectation is already set for the UserRepositoryInterface.GetUserById method")
	}

	if len(mmGetUserById.expectations) > 0 {
		mmGetUserById.mock.t.Fatalf("Some expectations are already set for the UserRepositoryInterface.GetUserById method")
	}

	mmGetUserById.mock.funcGetUserById = f
	mmGetUserById.mock.funcGetUserByIdOrigin = minimock.CallerInfo(1)
	return mmGetUserById.mock
}

// When sets expectation for the UserRepositoryInterface.GetUserById which will trigger the result defined by the following
// Then helper
func (mmGetUserById *mUserRepositoryInterfaceMockGetUserById) When(ctx context.Context, id int) *UserRepositoryInterfaceMockGetUserByIdExpectation {
	if mmGetUserById.mock.funcGetUserById != nil {
		mmGetUserById.mock.t.Fatalf("UserRepositoryInterfaceMock.GetUserById mock is already set by Set")
	}

	expectation := &UserRepositoryInterfaceMockGetUserByIdExpectation{
		mock:               mmGetUserById.mock,
		params:             &UserRepositoryInterfaceMockGetUserByIdParams{ctx, id},
		expectationOrigins: UserRepositoryInterfaceMockGetUserByIdExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetUserById.expectations = append(mmGetUserById.expectations, expectation)
	return expectation
}

// Then sets up UserRepositoryInterface.GetUserById return parameters for the expectation previously defined by the When method
func (e *UserRepositoryInterfaceMockGetUserByIdExpectation) Then(up1 *model.User, err error) *UserRepositoryInterfaceMock {
	e.results = &UserRepositoryInterfaceMockGetUserByIdResults{up1, err}
	return e.mock
}

// Times sets number of times UserRepositoryInterface.GetUserById should be invoked
func (mmGetUserById *mUserRepositoryInterfaceMockGetUserById) Times(n uint64) *mUserRepositoryInterfaceMockGetUserById {
	if n == 0 {
		mmGetUserById.mock.t.Fatalf("Times of UserRepositoryInterfaceMock.GetUserById mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetUserById.expectedInvocations, n)
	mmGetUserById.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetUserById
}

func (mmGetUserById *mUserRepositoryInterfaceMockGetUserById) invocationsDone() bool {
	if len(mmGetUserById.expectations) == 0 && mmGetUserById.defaultExpectation == nil && mmGetUserById.mock.funcGetUserById == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetUserById.mock.afterGetUserByIdCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetUserById.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetUserById implements mm_repository.UserRepositoryInterface
func (mmGetUserById *UserRepositoryInterfaceMock) GetUserById(ctx context.Context, id int) (up1 *model.User, err error) {
	mm_atomic.AddUint64(&mmGetUserById.beforeGetUserByIdCounter, 1)
	defer mm_atomic.AddUint64(&mmGetUserById.afterGetUserByIdCounter, 1)

	mmGetUserById.t.Helper()

	if mmGetUserById.inspectFuncGetUserById != nil {
		mmGetUserById.inspectFuncGetUserById(ctx, id)
	}

	mm_params := UserRepositoryInterfaceMockGetUserByIdParams{ctx, id}

	// Record call args
	mmGetUserById.GetUserByIdMock.mutex.Lock()
	mmGetUserById.GetUserByIdMock.callArgs = append(mmGetUserById.GetUserByIdMock.callArgs, &mm_params)
	mmGetUserById.GetUserByIdMock.mutex.Unlock()

	for _, e := range mmGetUserById.GetUserByIdMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmGetUserById.GetUserByIdMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetUserById.GetUserByIdMock.defaultExpectation.Counter, 1)
		mm_want := mmGetUserById.GetUserByIdMock.defaultExpectation.params
		mm_want_ptrs := mmGetUserById.GetUserByIdMock.defaultExpectation.paramPtrs

		mm_got := UserRepositoryInterfaceMockGetUserByIdParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetUserById.t.Errorf("UserRepositoryInterfaceMock.GetUserById got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetUserById.GetUserByIdMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmGetUserById.t.Errorf("UserRepositoryInterfaceMock.GetUserById got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetUserById.GetUserByIdMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetUserById.t.Errorf("UserRepositoryInterfaceMock.GetUserById got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetUserById.GetUserByIdMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetUserById.GetUserByIdMock.defaultExpectation.results
		if mm_results == nil {
			mmGetUserById.t.Fatal("No results are set for the UserRepositoryInterfaceMock.GetUserById")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmGetUserById.funcGetUserById != nil {
		return mmGetUserById.funcGetUserById(ctx, id)
	}
	mmGetUserById.t.Fatalf("Unexpected call to UserRepositoryInterfaceMock.GetUserById. %v %v", ctx, id)
	return
}

// GetUserByIdAfterCounter returns a count of finished UserRepositoryInterfaceMock.GetUserById invocations
func (mmGetUserById *UserRepositoryInterfaceMock) GetUserByIdAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUserById.afterGetUserByIdCounter)
}

// GetUserByIdBeforeCounter returns a count of UserRepositoryInterfaceMock.GetUserById invocations
func (mmGetUserById *UserRepositoryInterfaceMock) GetUserByIdBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUserById.beforeGetUserByIdCounter)
}

// Calls returns a list of arguments used in each call to UserRepositoryInterfaceMock.GetUserById.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetUserById *mUserRepositoryInterfaceMockGetUserById) Calls() []*UserRepositoryInterfaceMockGetUserByIdParams {
	mmGetUserById.mutex.RLock()

	argCopy := make([]*UserRepositoryInterfaceMockGetUserByIdParams, len(mmGetUserById.callArgs))
	copy(argCopy, mmGetUserById.callArgs)

	mmGetUserById.mutex.RUnlock()

	return argCopy
}

// MinimockGetUserByIdDone returns true if the count of the GetUserById invocations corresponds
// the number of defined expectations
func (m *UserRepositoryInterfaceMock) MinimockGetUserByIdDone() bool {
	if m.GetUserByIdMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetUserByIdMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetUserByIdMock.invocationsDone()
}

// MinimockGetUserByIdInspect logs each unmet expectation
func (m *UserRepositoryInterfaceMock) MinimockGetUserByIdInspect() {
	for _, e := range m.GetUserByIdMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserRepositoryInterfaceMock.GetUserById at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetUserByIdCounter := mm_atomic.LoadUint64(&m.afterGetUserByIdCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetUserByIdMock.defaultExpectation != nil && afterGetUserByIdCounter < 1 {
		if m.GetUserByIdMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserRepositoryInterfaceMock.GetUserById at\n%s", m.GetUserByIdMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserRepositoryInterfaceMock.GetUserById at\n%s with params: %#v", m.GetUserByIdMock.defaultExpectation.expectationOrigins.origin, *m.GetUserByIdMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetUserById != nil && afterGetUserByIdCounter < 1 {
		m.t.Errorf("Expected call to UserRepositoryInterfaceMock.GetUserById at\n%s", m.funcGetUserByIdOrigin)
	}

	if !m.GetUserByIdMock.invocationsDone() && afterGetUserByIdCounter > 0 {
		m.t.Errorf("Expected %d calls to UserRepositoryInterfaceMock.GetUserById at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetUserByIdMock.expectedInvocations), m.GetUserByIdMock.expectedInvocationsOrigin, afterGetUserByIdCounter)
	}
}

type mUserRepositoryInterfaceMockGetUserByName struct {
	optional           bool
	mock               *UserRepositoryInterfaceMock
	defaultExpectation *UserRepositoryInterfaceMockGetUserByNameExpectation
	expectations       []*UserRepositoryInterfaceMockGetUserByNameExpectation

	callArgs []*UserRepositoryInterfaceMockGetUserByNameParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserRepositoryInterfaceMockGetUserByNameExpectation specifies expectation struct of the UserRepositoryInterface.GetUserByName
type UserRepositoryInterfaceMockGetUserByNameExpectation struct {
	mock               *UserRepositoryInterfaceMock
	params             *UserRepositoryInterfaceMockGetUserByNameParams
	paramPtrs          *UserRepositoryInterfaceMockGetUserByNameParamPtrs
	expectationOrigins UserRepositoryInterfaceMockGetUserByNameExpectationOrigins
	results            *UserRepositoryInterfaceMockGetUserByNameResults
	returnOrigin       string
	Counter            uint64
}

// UserRepositoryInterfaceMockGetUserByNameParams contains parameters of the UserRepositoryInterface.GetUserByName
type UserRepositoryInterfaceMockGetUserByNameParams struct {
	ctx  context.Context
	name string
}

// UserRepositoryInterfaceMockGetUserByNameParamPtrs contains pointers to parameters of the UserRepositoryInterface.GetUserByName
type UserRepositoryInterfaceMockGetUserByNameParamPtrs struct {
	ctx  *context.Context
	name *string
}

// UserRepositoryInterfaceMockGetUserByNameResults contains results of the UserRepositoryInterface.GetUserByName
type UserRepositoryInterfaceMockGetUserByNameResults struct {
	up1 *model.User
	err error
}

// UserRepositoryInterfaceMockGetUserByNameOrigins contains origins of expectations of the UserRepositoryInterface.GetUserByName
type UserRepositoryInterfaceMockGetUserByNameExpectationOrigins struct {
	origin     string
	originCtx  string
	originName string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetUserByName *mUserRepositoryInterfaceMockGetUserByName) Optional() *mUserRepositoryInterfaceMockGetUserByName {
	mmGetUserByName.optional = true
	return mmGetUserByName
}

// Expect sets up expected params for UserRepositoryInterface.GetUserByName
func (mmGetUserByName *mUserRepositoryInterfaceMockGetUserByName) Expect(ctx context.Context, name string) *mUserRepositoryInterfaceMockGetUserByName {
	if mmGetUserByName.mock.funcGetUserByName != nil {
		mmGetUserByName.mock.t.Fatalf("UserRepositoryInterfaceMock.GetUserByName mock is already set by Set")
	}

	if mmGetUserByName.defaultExpectation == nil {
		mmGetUserByName.defaultExpectation = &UserRepositoryInterfaceMockGetUserByNameExpectation{}
	}

	if mmGetUserByName.defaultExpectation.paramPtrs != nil {
		mmGetUserByName.mock.t.Fatalf("UserRepositoryInterfaceMock.GetUserByName mock is already set by ExpectParams functions")
	}

	mmGetUserByName.defaultExpectation.params = &UserRepositoryInterfaceMockGetUserByNameParams{ctx, name}
	mmGetUserByName.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetUserByName.expectations {
		if minimock.Equal(e.params, mmGetUserByName.defaultExpectation.params) {
			mmGetUserByName.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetUserByName.defaultExpectation.params)
		}
	}

	return mmGetUserByName
}

// ExpectCtxParam1 sets up expected param ctx for UserRepositoryInterface.GetUserByName
func (mmGetUserByName *mUserRepositoryInterfaceMockGetUserByName) ExpectCtxParam1(ctx context.Context) *mUserRepositoryInterfaceMockGetUserByName {
	if mmGetUserByName.mock.funcGetUserByName != nil {
		mmGetUserByName.mock.t.Fatalf("UserRepositoryInterfaceMock.GetUserByName mock is already set by Set")
	}

	if mmGetUserByName.defaultExpectation == nil {
		mmGetUserByName.defaultExpectation = &UserRepositoryInterfaceMockGetUserByNameExpectation{}
	}

	if mmGetUserByName.defaultExpectation.params != nil {
		mmGetUserByName.mock.t.Fatalf("UserRepositoryInterfaceMock.GetUserByName mock is already set by Expect")
	}

	if mmGetUserByName.defaultExpectation.paramPtrs == nil {
		mmGetUserByName.defaultExpectation.paramPtrs = &UserRepositoryInterfaceMockGetUserByNameParamPtrs{}
	}
	mmGetUserByName.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetUserByName.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetUserByName
}

// ExpectNameParam2 sets up expected param name for UserRepositoryInterface.GetUserByName
func (mmGetUserByName *mUserRepositoryInterfaceMockGetUserByName) ExpectNameParam2(name string) *mUserRepositoryInterfaceMockGetUserByName {
	if mmGetUserByName.mock.funcGetUserByName != nil {
		mmGetUserByName.mock.t.Fatalf("UserRepositoryInterfaceMock.GetUserByName mock is already set by Set")
	}

	if mmGetUserByName.defaultExpectation == nil {
		mmGetUserByName.defaultExpectation = &UserRepositoryInterfaceMockGetUserByNameExpectation{}
	}

	if mmGetUserByName.defaultExpectation.params != nil {
		mmGetUserByName.mock.t.Fatalf("UserRepositoryInterfaceMock.GetUserByName mock is already set by Expect")
	}

	if mmGetUserByName.defaultExpectation.paramPtrs == nil {
		mmGetUserByName.defaultExpectation.paramPtrs = &UserRepositoryInterfaceMockGetUserByNameParamPtrs{}
	}
	mmGetUserByName.defaultExpectation.paramPtrs.name = &name
	mmGetUserByName.defaultExpectation.expectationOrigins.originName = minimock.CallerInfo(1)

	return mmGetUserByName
}

// Inspect accepts an inspector function that has same arguments as the UserRepositoryInterface.GetUserByName
func (mmGetUserByName *mUserRepositoryInterfaceMockGetUserByName) Inspect(f func(ctx context.Context, name string)) *mUserRepositoryInterfaceMockGetUserByName {
	if mmGetUserByName.mock.inspectFuncGetUserByName != nil {
		mmGetUserByName.mock.t.Fatalf("Inspect function is already set for UserRepositoryInterfaceMock.GetUserByName")
	}

	mmGetUserByName.mock.inspectFuncGetUserByName = f

	return mmGetUserByName
}

// Return sets up results that will be returned by UserRepositoryInterface.GetUserByName
func (mmGetUserByName *mUserRepositoryInterfaceMockGetUserByName) Return(up1 *model.User, err error) *UserRepositoryInterfaceMock {
	if mmGetUserByName.mock.funcGetUserByName != nil {
		mmGetUserByName.mock.t.Fatalf("UserRepositoryInterfaceMock.GetUserByName mock is already set by Set")
	}

	if mmGetUserByName.defaultExpectation == nil {
		mmGetUserByName.defaultExpectation = &UserRepositoryInterfaceMockGetUserByNameExpectation{mock: mmGetUserByName.mock}
	}
	mmGetUserByName.defaultExpectation.results = &UserRepositoryInterfaceMockGetUserByNameResults{up1, err}
	mmGetUserByName.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetUserByName.mock
}

// Set uses given function f to mock the UserRepositoryInterface.GetUserByName method
func (mmGetUserByName *mUserRepositoryInterfaceMockGetUserByName) Set(f func(ctx context.Context, name string) (up1 *model.User, err error)) *UserRepositoryInterfaceMock {
	if mmGetUserByName.defaultExpectation != nil {
		mmGetUserByName.mock.t.Fatalf("Default expectation is already set for the UserRepositoryInterface.GetUserByName method")
	}

	if len(mmGetUserByName.expectations) > 0 {
		mmGetUserByName.mock.t.Fatalf("Some expectations are already set for the UserRepositoryInterface.GetUserByName method")
	}

	mmGetUserByName.mock.funcGetUserByName = f
	mmGetUserByName.mock.funcGetUserByNameOrigin = minimock.CallerInfo(1)
	return mmGetUserByName.mock
}

// When sets expectation for the UserRepositoryInterface.GetUserByName which will trigger the result defined by the following
// Then helper
func (mmGetUserByName *mUserRepositoryInterfaceMockGetUserByName) When(ctx context.Context, name string) *UserRepositoryInterfaceMockGetUserByNameExpectation {
	if mmGetUserByName.mock.funcGetUserByName != nil {
		mmGetUserByName.mock.t.Fatalf("UserRepositoryInterfaceMock.GetUserByName mock is already set by Set")
	}

	expectation := &UserRepositoryInterfaceMockGetUserByNameExpectation{
		mock:               mmGetUserByName.mock,
		params:             &UserRepositoryInterfaceMockGetUserByNameParams{ctx, name},
		expectationOrigins: UserRepositoryInterfaceMockGetUserByNameExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetUserByName.expectations = append(mmGetUserByName.expectations, expectation)
	return expectation
}

// Then sets up UserRepositoryInterface.GetUserByName return parameters for the expectation previously defined by the When method
func (e *UserRepositoryInterfaceMockGetUserByNameExpectation) Then(up1 *model.User, err error) *UserRepositoryInterfaceMock {
	e.results = &UserRepositoryInterfaceMockGetUserByNameResults{up1, err}
	return e.mock
}

// Times sets number of times UserRepositoryInterface.GetUserByName should be invoked
func (mmGetUserByName *mUserRepositoryInterfaceMockGetUserByName) Times(n uint64) *mUserRepositoryInterfaceMockGetUserByName {
	if n == 0 {
		mmGetUserByName.mock.t.Fatalf("Times of UserRepositoryInterfaceMock.GetUserByName mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetUserByName.expectedInvocations, n)
	mmGetUserByName.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetUserByName
}

func (mmGetUserByName *mUserRepositoryInterfaceMockGetUserByName) invocationsDone() bool {
	if len(mmGetUserByName.expectations) == 0 && mmGetUserByName.defaultExpectation == nil && mmGetUserByName.mock.funcGetUserByName == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetUserByName.mock.afterGetUserByNameCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetUserByName.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetUserByName implements mm_repository.UserRepositoryInterface
func (mmGetUserByName *UserRepositoryInterfaceMock) GetUserByName(ctx context.Context, name string) (up1 *model.User, err error) {
	mm_atomic.AddUint64(&mmGetUserByName.beforeGetUserByNameCounter, 1)
	defer mm_atomic.AddUint64(&mmGetUserByName.afterGetUserByNameCounter, 1)

	mmGetUserByName.t.Helper()

	if mmGetUserByName.inspectFuncGetUserByName != nil {
		mmGetUserByName.inspectFuncGetUserByName(ctx, name)
	}

	mm_params := UserRepositoryInterfaceMockGetUserByNameParams{ctx, name}

	// Record call args
	mmGetUserByName.GetUserByNameMock.mutex.Lock()
	mmGetUserByName.GetUserByNameMock.callArgs = append(mmGetUserByName.GetUserByNameMock.callArgs, &mm_params)
	mmGetUserByName.GetUserByNameMock.mutex.Unlock()

	for _, e := range mmGetUserByName.GetUserByNameMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmGetUserByName.GetUserByNameMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetUserByName.GetUserByNameMock.defaultExpectation.Counter, 1)
		mm_want := mmGetUserByName.GetUserByNameMock.defaultExpectation.params
		mm_want_ptrs := mmGetUserByName.GetUserByNameMock.defaultExpectation.paramPtrs

		mm_got := UserRepositoryInterfaceMockGetUserByNameParams{ctx, name}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetUserByName.t.Errorf("UserRepositoryInterfaceMock.GetUserByName got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetUserByName.GetUserByNameMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.name != nil && !minimock.Equal(*mm_want_ptrs.name, mm_got.name) {
				mmGetUserByName.t.Errorf("UserRepositoryInterfaceMock.GetUserByName got unexpected parameter name, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetUserByName.GetUserByNameMock.defaultExpectation.expectationOrigins.originName, *mm_want_ptrs.name, mm_got.name, minimock.Diff(*mm_want_ptrs.name, mm_got.name))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetUserByName.t.Errorf("UserRepositoryInterfaceMock.GetUserByName got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetUserByName.GetUserByNameMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetUserByName.GetUserByNameMock.defaultExpectation.results
		if mm_results == nil {
			mmGetUserByName.t.Fatal("No results are set for the UserRepositoryInterfaceMock.GetUserByName")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmGetUserByName.funcGetUserByName != nil {
		return mmGetUserByName.funcGetUserByName(ctx, name)
	}
	mmGetUserByName.t.Fatalf("Unexpected call to UserRepositoryInterfaceMock.GetUserByName. %v %v", ctx, name)
	return
}

// GetUserByNameAfterCounter returns a count of finished UserRepositoryInterfaceMock.GetUserByName invocations
func (mmGetUserByName *UserRepositoryInterfaceMock) GetUserByNameAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUserByName.afterGetUserByNameCounter)
}

// GetUserByNameBeforeCounter returns a count of UserRepositoryInterfaceMock.GetUserByName invocations
func (mmGetUserByName *UserRepositoryInterfaceMock) GetUserByNameBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUserByName.beforeGetUserByNameCounter)
}

// Calls returns a list of arguments used in each call to UserRepositoryInterfaceMock.GetUserByName.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetUserByName *mUserRepositoryInterfaceMockGetUserByName) Calls() []*UserRepositoryInterfaceMockGetUserByNameParams {
	mmGetUserByName.mutex.RLock()

	argCopy := make([]*UserRepositoryInterfaceMockGetUserByNameParams, len(mmGetUserByName.callArgs))
	copy(argCopy, mmGetUserByName.callArgs)

	mmGetUserByName.mutex.RUnlock()

	return argCopy
}

// MinimockGetUserByNameDone returns true if the count of the GetUserByName invocations corresponds
// the number of defined expectations
func (m *UserRepositoryInterfaceMock) MinimockGetUserByNameDone() bool {
	if m.GetUserByNameMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetUserByNameMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetUserByNameMock.invocationsDone()
}

// MinimockGetUserByNameInspect logs each unmet expectation
func (m *UserRepositoryInterfaceMock) MinimockGetUserByNameInspect() {
	for _, e := range m.GetUserByNameMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserRepositoryInterfaceMock.GetUserByName at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetUserByNameCounter := mm_atomic.LoadUint64(&m.afterGetUserByNameCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetUserByNameMock.defaultExpectation != nil && afterGetUserByNameCounter < 1 {
		if m.GetUserByNameMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserRepositoryInterfaceMock.GetUserByName at\n%s", m.GetUserByNameMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserRepositoryInterfaceMock.GetUserByName at\n%s with params: %#v", m.GetUserByNameMock.defaultExpectation.expectationOrigins.origin, *m.GetUserByNameMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetUserByName != nil && afterGetUserByNameCounter < 1 {
		m.t.Errorf("Expected call to UserRepositoryInterfaceMock.GetUserByName at\n%s", m.funcGetUserByNameOrigin)
	}

	if !m.GetUserByNameMock.invocationsDone() && afterGetUserByNameCounter > 0 {
		m.t.Errorf("Expected %d calls to UserRepositoryInterfaceMock.GetUserByName at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetUserByNameMock.expectedInvocations), m.GetUserByNameMock.expectedInvocationsOrigin, afterGetUserByNameCounter)
	}
}

type mUserRepositoryInterfaceMockSave struct {
	optional           bool
	mock               *UserRepositoryInterfaceMock
	defaultExpectation *UserRepositoryInterfaceMockSaveExpectation
	expectations       []*UserRepositoryInterfaceMockSaveExpectation

	callArgs []*UserRepositoryInterfaceMockSaveParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserRepositoryInterfaceMockSaveExpectation specifies expectation struct of the UserRepositoryInterface.Save
type UserRepositoryInterfaceMockSaveExpectation struct {
	mock               *UserRepositoryInterfaceMock
	params             *UserRepositoryInterfaceMockSaveParams
	paramPtrs          *UserRepositoryInterfaceMockSaveParamPtrs
	expectationOrigins UserRepositoryInterfaceMockSaveExpectationOrigins
	results            *UserRepositoryInterfaceMockSaveResults
	returnOrigin       string
	Counter            uint64
}

// UserRepositoryInterfaceMockSaveParams contains parameters of the UserRepositoryInterface.Save
type UserRepositoryInterfaceMockSaveParams struct {
	ctx  context.Context
	user model.User
}

// UserRepositoryInterfaceMockSaveParamPtrs contains pointers to parameters of the UserRepositoryInterface.Save
type UserRepositoryInterfaceMockSaveParamPtrs struct {
	ctx  *context.Context
	user *model.User
}

// UserRepositoryInterfaceMockSaveResults contains results of the UserRepositoryInterface.Save
type UserRepositoryInterfaceMockSaveResults struct {
	i1  int
	err error
}

// UserRepositoryInterfaceMockSaveOrigins contains origins of expectations of the UserRepositoryInterface.Save
type UserRepositoryInterfaceMockSaveExpectationOrigins struct {
	origin     string
	originCtx  string
	originUser string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSave *mUserRepositoryInterfaceMockSave) Optional() *mUserRepositoryInterfaceMockSave {
	mmSave.optional = true
	return mmSave
}

// Expect sets up expected params for UserRepositoryInterface.Save
func (mmSave *mUserRepositoryInterfaceMockSave) Expect(ctx context.Context, user model.User) *mUserRepositoryInterfaceMockSave {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("UserRepositoryInterfaceMock.Save mock is already set by Set")
	}

	if mmSave.defaultExpectation == nil {
		mmSave.defaultExpectation = &UserRepositoryInterfaceMockSaveExpectation{}
	}

	if mmSave.defaultExpectation.paramPtrs != nil {
		mmSave.mock.t.Fatalf("UserRepositoryInterfaceMock.Save mock is already set by ExpectParams functions")
	}

	mmSave.defaultExpectation.params = &UserRepositoryInterfaceMockSaveParams{ctx, user}
	mmSave.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSave.expectations {
		if minimock.Equal(e.params, mmSave.defaultExpectation.params) {
			mmSave.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSave.defaultExpectation.params)
		}
	}

	return mmSave
}

// ExpectCtxParam1 sets up expected param ctx for UserRepositoryInterface.Save
func (mmSave *mUserRepositoryInterfaceMockSave) ExpectCtxParam1(ctx context.Context) *mUserRepositoryInterfaceMockSave {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("UserRepositoryInterfaceMock.Save mock is already set by Set")
	}

	if mmSave.defaultExpectation == nil {
		mmSave.defaultExpectation = &UserRepositoryInterfaceMockSaveExpectation{}
	}

	if mmSave.defaultExpectation.params != nil {
		mmSave.mock.t.Fatalf("UserRepositoryInterfaceMock.Save mock is already set by Expect")
	}

	if mmSave.defaultExpectation.paramPtrs == nil {
		mmSave.defaultExpectation.paramPtrs = &UserRepositoryInterfaceMockSaveParamPtrs{}
	}
	mmSave.defaultExpectation.paramPtrs.ctx = &ctx
	mmSave.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSave
}

// ExpectUserParam2 sets up expected param user for UserRepositoryInterface.Save
func (mmSave *mUserRepositoryInterfaceMockSave) ExpectUserParam2(user model.User) *mUserRepositoryInterfaceMockSave {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("UserRepositoryInterfaceMock.Save mock is already set by Set")
	}

	if mmSave.defaultExpectation == nil {
		mmSave.defaultExpectation = &UserRepositoryInterfaceMockSaveExpectation{}
	}

	if mmSave.defaultExpectation.params != nil {
		mmSave.mock.t.Fatalf("UserRepositoryInterfaceMock.Save mock is already set by Expect")
	}

	if mmSave.defaultExpectation.paramPtrs == nil {
		mmSave.defaultExpectation.paramPtrs = &UserRepositoryInterfaceMockSaveParamPtrs{}
	}
	mmSave.defaultExpectation.paramPtrs.user = &user
	mmSave.defaultExpectation.expectationOrigins.originUser = minimock.CallerInfo(1)

	return mmSave
}

// Inspect accepts an inspector function that has same arguments as the UserRepositoryInterface.Save
func (mmSave *mUserRepositoryInterfaceMockSave) Inspect(f func(ctx context.Context, user model.User)) *mUserRepositoryInterfaceMockSave {
	if mmSave.mock.inspectFuncSave != nil {
		mmSave.mock.t.Fatalf("Inspect function is already set for UserRepositoryInterfaceMock.Save")
	}

	mmSave.mock.inspectFuncSave = f

	return mmSave
}

// Return sets up results that will be returned by UserRepositoryInterface.Save
func (mmSave *mUserRepositoryInterfaceMockSave) Return(i1 int, err error) *UserRepositoryInterfaceMock {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("UserRepositoryInterfaceMock.Save mock is already set by Set")
	}

	if mmSave.defaultExpectation == nil {
		mmSave.defaultExpectation = &UserRepositoryInterfaceMockSaveExpectation{mock: mmSave.mock}
	}
	mmSave.defaultExpectation.results = &UserRepositoryInterfaceMockSaveResults{i1, err}
	mmSave.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSave.mock
}

// Set uses given function f to mock the UserRepositoryInterface.Save method
func (mmSave *mUserRepositoryInterfaceMockSave) Set(f func(ctx context.Context, user model.User) (i1 int, err error)) *UserRepositoryInterfaceMock {
	if mmSave.defaultExpectation != nil {
		mmSave.mock.t.Fatalf("Default expectation is already set for the UserRepositoryInterface.Save method")
	}

	if len(mmSave.expectations) > 0 {
		mmSave.mock.t.Fatalf("Some expectations are already set for the UserRepositoryInterface.Save method")
	}

	mmSave.mock.funcSave = f
	mmSave.mock.funcSaveOrigin = minimock.CallerInfo(1)
	return mmSave.mock
}

// When sets expectation for the UserRepositoryInterface.Save which will trigger the result defined by the following
// Then helper
func (mmSave *mUserRepositoryInterfaceMockSave) When(ctx context.Context, user model.User) *UserRepositoryInterfaceMockSaveExpectation {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("UserRepositoryInterfaceMock.Save mock is already set by Set")
	}

	expectation := &UserRepositoryInterfaceMockSaveExpectation{
		mock:               mmSave.mock,
		params:             &UserRepositoryInterfaceMockSaveParams{ctx, user},
		expectationOrigins: UserRepositoryInterfaceMockSaveExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSave.expectations = append(mmSave.expectations, expectation)
	return expectation
}

// Then sets up UserRepositoryInterface.Save return parameters for the expectation previously defined by the When method
func (e *UserRepositoryInterfaceMockSaveExpectation) Then(i1 int, err error) *UserRepositoryInterfaceMock {
	e.results = &UserRepositoryInterfaceMockSaveResults{i1, err}
	return e.mock
}

// Times sets number of times UserRepositoryInterface.Save should be invoked
func (mmSave *mUserRepositoryInterfaceMockSave) Times(n uint64) *mUserRepositoryInterfaceMockSave {
	if n == 0 {
		mmSave.mock.t.Fatalf("Times of UserRepositoryInterfaceMock.Save mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSave.expectedInvocations, n)
	mmSave.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSave
}

func (mmSave *mUserRepositoryInterfaceMockSave) invocationsDone() bool {
	if len(mmSave.expectations) == 0 && mmSave.defaultExpectation == nil && mmSave.mock.funcSave == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSave.mock.afterSaveCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSave.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Save implements mm_repository.UserRepositoryInterface
func (mmSave *UserRepositoryInterfaceMock) Save(ctx context.Context, user model.User) (i1 int, err error) {
	mm_atomic.AddUint64(&mmSave.beforeSaveCounter, 1)
	defer mm_atomic.AddUint64(&mmSave.afterSaveCounter, 1)

	mmSave.t.Helper()

	if mmSave.inspectFuncSave != nil {
		mmSave.inspectFuncSave(ctx, user)
	}

	mm_params := UserRepositoryInterfaceMockSaveParams{ctx, user}

	// Record call args
	mmSave.SaveMock.mutex.Lock()
	mmSave.SaveMock.callArgs = append(mmSave.SaveMock.callArgs, &mm_params)
	mmSave.SaveMock.mutex.Unlock()

	for _, e := range mmSave.SaveMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmSave.SaveMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSave.SaveMock.defaultExpectation.Counter, 1)
		mm_want := mmSave.SaveMock.defaultExpectation.params
		mm_want_ptrs := mmSave.SaveMock.defaultExpectation.paramPtrs

		mm_got := UserRepositoryInterfaceMockSaveParams{ctx, user}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSave.t.Errorf("UserRepositoryInterfaceMock.Save got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSave.SaveMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.user != nil && !minimock.Equal(*mm_want_ptrs.user, mm_got.user) {
				mmSave.t.Errorf("UserRepositoryInterfaceMock.Save got unexpected parameter user, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSave.SaveMock.defaultExpectation.expectationOrigins.originUser, *mm_want_ptrs.user, mm_got.user, minimock.Diff(*mm_want_ptrs.user, mm_got.user))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSave.t.Errorf("UserRepositoryInterfaceMock.Save got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSave.SaveMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSave.SaveMock.defaultExpectation.results
		if mm_results == nil {
			mmSave.t.Fatal("No results are set for the UserRepositoryInterfaceMock.Save")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmSave.funcSave != nil {
		return mmSave.funcSave(ctx, user)
	}
	mmSave.t.Fatalf("Unexpected call to UserRepositoryInterfaceMock.Save. %v %v", ctx, user)
	return
}

// SaveAfterCounter returns a count of finished UserRepositoryInterfaceMock.Save invocations
func (mmSave *UserRepositoryInterfaceMock) SaveAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSave.afterSaveCounter)
}

// SaveBeforeCounter returns a count of UserRepositoryInterfaceMock.Save invocations
func (mmSave *UserRepositoryInterfaceMock) SaveBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSave.beforeSaveCounter)
}

// Calls returns a list of arguments used in each call to UserRepositoryInterfaceMock.Save.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSave *mUserRepositoryInterfaceMockSave) Calls() []*UserRepositoryInterfaceMockSaveParams {
	mmSave.mutex.RLock()

	argCopy := make([]*UserRepositoryInterfaceMockSaveParams, len(mmSave.callArgs))
	copy(argCopy, mmSave.callArgs)

	mmSave.mutex.RUnlock()

	return argCopy
}

// MinimockSaveDone returns true if the count of the Save invocations corresponds
// the number of defined expectations
func (m *UserRepositoryInterfaceMock) MinimockSaveDone() bool {
	if m.SaveMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SaveMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SaveMock.invocationsDone()
}

// MinimockSaveInspect logs each unmet expectation
func (m *UserRepositoryInterfaceMock) MinimockSaveInspect() {
	for _, e := range m.SaveMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserRepositoryInterfaceMock.Save at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSaveCounter := mm_atomic.LoadUint64(&m.afterSaveCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SaveMock.defaultExpectation != nil && afterSaveCounter < 1 {
		if m.SaveMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserRepositoryInterfaceMock.Save at\n%s", m.SaveMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserRepositoryInterfaceMock.Save at\n%s with params: %#v", m.SaveMock.defaultExpectation.expectationOrigins.origin, *m.SaveMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSave != nil && afterSaveCounter < 1 {
		m.t.Errorf("Expected call to UserRepositoryInterfaceMock.Save at\n%s", m.funcSaveOrigin)
	}

	if !m.SaveMock.invocationsDone() && afterSaveCounter > 0 {
		m.t.Errorf("Expected %d calls to UserRepositoryInterfaceMock.Save at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SaveMock.expectedInvocations), m.SaveMock.expectedInvocationsOrigin, afterSaveCounter)
	}
}

type mUserRepositoryInterfaceMockUpdate struct {
	optional           bool
	mock               *UserRepositoryInterfaceMock
	defaultExpectation *UserRepositoryInterfaceMockUpdateExpectation
	expectations       []*UserRepositoryInterfaceMockUpdateExpectation

	callArgs []*UserRepositoryInterfaceMockUpdateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserRepositoryInterfaceMockUpdateExpectation specifies expectation struct of the UserRepositoryInterface.Update
type UserRepositoryInterfaceMockUpdateExpectation struct {
	mock               *UserRepositoryInterfaceMock
	params             *UserRepositoryInterfaceMockUpdateParams
	paramPtrs          *UserRepositoryInterfaceMockUpdateParamPtrs
	expectationOrigins UserRepositoryInterfaceMockUpdateExpectationOrigins
	results            *UserRepositoryInterfaceMockUpdateResults
	returnOrigin       string
	Counter            uint64
}

// UserRepositoryInterfaceMockUpdateParams contains parameters of the UserRepositoryInterface.Update
type UserRepositoryInterfaceMockUpdateParams struct {
	ctx    context.Context
	update model.User
}

// UserRepositoryInterfaceMockUpdateParamPtrs contains pointers to parameters of the UserRepositoryInterface.Update
type UserRepositoryInterfaceMockUpdateParamPtrs struct {
	ctx    *context.Context
	update *model.User
}

// UserRepositoryInterfaceMockUpdateResults contains results of the UserRepositoryInterface.Update
type UserRepositoryInterfaceMockUpdateResults struct {
	err error
}

// UserRepositoryInterfaceMockUpdateOrigins contains origins of expectations of the UserRepositoryInterface.Update
type UserRepositoryInterfaceMockUpdateExpectationOrigins struct {
	origin       string
	originCtx    string
	originUpdate string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUpdate *mUserRepositoryInterfaceMockUpdate) Optional() *mUserRepositoryInterfaceMockUpdate {
	mmUpdate.optional = true
	return mmUpdate
}

// Expect sets up expected params for UserRepositoryInterface.Update
func (mmUpdate *mUserRepositoryInterfaceMockUpdate) Expect(ctx context.Context, update model.User) *mUserRepositoryInterfaceMockUpdate {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("UserRepositoryInterfaceMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &UserRepositoryInterfaceMockUpdateExpectation{}
	}

	if mmUpdate.defaultExpectation.paramPtrs != nil {
		mmUpdate.mock.t.Fatalf("UserRepositoryInterfaceMock.Update mock is already set by ExpectParams functions")
	}

	mmUpdate.defaultExpectation.params = &UserRepositoryInterfaceMockUpdateParams{ctx, update}
	mmUpdate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUpdate.expectations {
		if minimock.Equal(e.params, mmUpdate.defaultExpectation.params) {
			mmUpdate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdate.defaultExpectation.params)
		}
	}

	return mmUpdate
}

// ExpectCtxParam1 sets up expected param ctx for UserRepositoryInterface.Update
func (mmUpdate *mUserRepositoryInterfaceMockUpdate) ExpectCtxParam1(ctx context.Context) *mUserRepositoryInterfaceMockUpdate {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("UserRepositoryInterfaceMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &UserRepositoryInterfaceMockUpdateExpectation{}
	}

	if mmUpdate.defaultExpectation.params != nil {
		mmUpdate.mock.t.Fatalf("UserRepositoryInterfaceMock.Update mock is already set by Expect")
	}

	if mmUpdate.defaultExpectation.paramPtrs == nil {
		mmUpdate.defaultExpectation.paramPtrs = &UserRepositoryInterfaceMockUpdateParamPtrs{}
	}
	mmUpdate.defaultExpectation.paramPtrs.ctx = &ctx
	mmUpdate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmUpdate
}

// ExpectUpdateParam2 sets up expected param update for UserRepositoryInterface.Update
func (mmUpdate *mUserRepositoryInterfaceMockUpdate) ExpectUpdateParam2(update model.User) *mUserRepositoryInterfaceMockUpdate {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("UserRepositoryInterfaceMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &UserRepositoryInterfaceMockUpdateExpectation{}
	}

	if mmUpdate.defaultExpectation.params != nil {
		mmUpdate.mock.t.Fatalf("UserRepositoryInterfaceMock.Update mock is already set by Expect")
	}

	if mmUpdate.defaultExpectation.paramPtrs == nil {
		mmUpdate.defaultExpectation.paramPtrs = &UserRepositoryInterfaceMockUpdateParamPtrs{}
	}
	mmUpdate.defaultExpectation.paramPtrs.update = &update
	mmUpdate.defaultExpectation.expectationOrigins.originUpdate = minimock.CallerInfo(1)

	return mmUpdate
}

// Inspect accepts an inspector function that has same arguments as the UserRepositoryInterface.Update
func (mmUpdate *mUserRepositoryInterfaceMockUpdate) Inspect(f func(ctx context.Context, update model.User)) *mUserRepositoryInterfaceMockUpdate {
	if mmUpdate.mock.inspectFuncUpdate != nil {
		mmUpdate.mock.t.Fatalf("Inspect function is already set for UserRepositoryInterfaceMock.Update")
	}

	mmUpdate.mock.inspectFuncUpdate = f

	return mmUpdate
}

// Return sets up results that will be returned by UserRepositoryInterface.Update
func (mmUpdate *mUserRepositoryInterfaceMockUpdate) Return(err error) *UserRepositoryInterfaceMock {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("UserRepositoryInterfaceMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &UserRepositoryInterfaceMockUpdateExpectation{mock: mmUpdate.mock}
	}
	mmUpdate.defaultExpectation.results = &UserRepositoryInterfaceMockUpdateResults{err}
	mmUpdate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUpdate.mock
}

// Set uses given function f to mock the UserRepositoryInterface.Update method
func (mmUpdate *mUserRepositoryInterfaceMockUpdate) Set(f func(ctx context.Context, update model.User) (err error)) *UserRepositoryInterfaceMock {
	if mmUpdate.defaultExpectation != nil {
		mmUpdate.mock.t.Fatalf("Default expectation is already set for the UserRepositoryInterface.Update method")
	}

	if len(mmUpdate.expectations) > 0 {
		mmUpdate.mock.t.Fatalf("Some expectations are already set for the UserRepositoryInterface.Update method")
	}

	mmUpdate.mock.funcUpdate = f
	mmUpdate.mock.funcUpdateOrigin = minimock.CallerInfo(1)
	return mmUpdate.mock
}

// When sets expectation for the UserRepositoryInterface.Update which will trigger the result defined by the following
// Then helper
func (mmUpdate *mUserRepositoryInterfaceMockUpdate) When(ctx context.Context, update model.User) *UserRepositoryInterfaceMockUpdateExpectation {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("UserRepositoryInterfaceMock.Update mock is already set by Set")
	}

	expectation := &UserRepositoryInterfaceMockUpdateExpectation{
		mock:               mmUpdate.mock,
		params:             &UserRepositoryInterfaceMockUpdateParams{ctx, update},
		expectationOrigins: UserRepositoryInterfaceMockUpdateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUpdate.expectations = append(mmUpdate.expectations, expectation)
	return expectation
}

// Then sets up UserRepositoryInterface.Update return parameters for the expectation previously defined by the When method
func (e *UserRepositoryInterfaceMockUpdateExpectation) Then(err error) *UserRepositoryInterfaceMock {
	e.results = &UserRepositoryInterfaceMockUpdateResults{err}
	return e.mock
}

// Times sets number of times UserRepositoryInterface.Update should be invoked
func (mmUpdate *mUserRepositoryInterfaceMockUpdate) Times(n uint64) *mUserRepositoryInterfaceMockUpdate {
	if n == 0 {
		mmUpdate.mock.t.Fatalf("Times of UserRepositoryInterfaceMock.Update mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUpdate.expectedInvocations, n)
	mmUpdate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUpdate
}

func (mmUpdate *mUserRepositoryInterfaceMockUpdate) invocationsDone() bool {
	if len(mmUpdate.expectations) == 0 && mmUpdate.defaultExpectation == nil && mmUpdate.mock.funcUpdate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUpdate.mock.afterUpdateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUpdate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Update implements mm_repository.UserRepositoryInterface
func (mmUpdate *UserRepositoryInterfaceMock) Update(ctx context.Context, update model.User) (err error) {
	mm_atomic.AddUint64(&mmUpdate.beforeUpdateCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdate.afterUpdateCounter, 1)

	mmUpdate.t.Helper()

	if mmUpdate.inspectFuncUpdate != nil {
		mmUpdate.inspectFuncUpdate(ctx, update)
	}

	mm_params := UserRepositoryInterfaceMockUpdateParams{ctx, update}

	// Record call args
	mmUpdate.UpdateMock.mutex.Lock()
	mmUpdate.UpdateMock.callArgs = append(mmUpdate.UpdateMock.callArgs, &mm_params)
	mmUpdate.UpdateMock.mutex.Unlock()

	for _, e := range mmUpdate.UpdateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmUpdate.UpdateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdate.UpdateMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdate.UpdateMock.defaultExpectation.params
		mm_want_ptrs := mmUpdate.UpdateMock.defaultExpectation.paramPtrs

		mm_got := UserRepositoryInterfaceMockUpdateParams{ctx, update}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmUpdate.t.Errorf("UserRepositoryInterfaceMock.Update got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdate.UpdateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.update != nil && !minimock.Equal(*mm_want_ptrs.update, mm_got.update) {
				mmUpdate.t.Errorf("UserRepositoryInterfaceMock.Update got unexpected parameter update, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdate.UpdateMock.defaultExpectation.expectationOrigins.originUpdate, *mm_want_ptrs.update, mm_got.update, minimock.Diff(*mm_want_ptrs.update, mm_got.update))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdate.t.Errorf("UserRepositoryInterfaceMock.Update got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUpdate.UpdateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdate.UpdateMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdate.t.Fatal("No results are set for the UserRepositoryInterfaceMock.Update")
		}
		return (*mm_results).err
	}
	if mmUpdate.funcUpdate != nil {
		return mmUpdate.funcUpdate(ctx, update)
	}
	mmUpdate.t.Fatalf("Unexpected call to UserRepositoryInterfaceMock.Update. %v %v", ctx, update)
	return
}

// UpdateAfterCounter returns a count of finished UserRepositoryInterfaceMock.Update invocations
func (mmUpdate *UserRepositoryInterfaceMock) UpdateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdate.afterUpdateCounter)
}

// UpdateBeforeCounter returns a count of UserRepositoryInterfaceMock.Update invocations
func (mmUpdate *UserRepositoryInterfaceMock) UpdateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdate.beforeUpdateCounter)
}

// Calls returns a list of arguments used in each call to UserRepositoryInterfaceMock.Update.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdate *mUserRepositoryInterfaceMockUpdate) Calls() []*UserRepositoryInterfaceMockUpdateParams {
	mmUpdate.mutex.RLock()

	argCopy := make([]*UserRepositoryInterfaceMockUpdateParams, len(mmUpdate.callArgs))
	copy(argCopy, mmUpdate.callArgs)

	mmUpdate.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateDone returns true if the count of the Update invocations corresponds
// the number of defined expectations
func (m *UserRepositoryInterfaceMock) MinimockUpdateDone() bool {
	if m.UpdateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UpdateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UpdateMock.invocationsDone()
}

// MinimockUpdateInspect logs each unmet expectation
func (m *UserRepositoryInterfaceMock) MinimockUpdateInspect() {
	for _, e := range m.UpdateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserRepositoryInterfaceMock.Update at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUpdateCounter := mm_atomic.LoadUint64(&m.afterUpdateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateMock.defaultExpectation != nil && afterUpdateCounter < 1 {
		if m.UpdateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserRepositoryInterfaceMock.Update at\n%s", m.UpdateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserRepositoryInterfaceMock.Update at\n%s with params: %#v", m.UpdateMock.defaultExpectation.expectationOrigins.origin, *m.UpdateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdate != nil && afterUpdateCounter < 1 {
		m.t.Errorf("Expected call to UserRepositoryInterfaceMock.Update at\n%s", m.funcUpdateOrigin)
	}

	if !m.UpdateMock.invocationsDone() && afterUpdateCounter > 0 {
		m.t.Errorf("Expected %d calls to UserRepositoryInterfaceMock.Update at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UpdateMock.expectedInvocations), m.UpdateMock.expectedInvocationsOrigin, afterUpdateCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UserRepositoryInterfaceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockDeleteInspect()

			m.MinimockGetUserByIdInspect()

			m.MinimockGetUserByNameInspect()

			m.MinimockSaveInspect()

			m.MinimockUpdateInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UserRepositoryInterfaceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UserRepositoryInterfaceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDeleteDone() &&
		m.MinimockGetUserByIdDone() &&
		m.MinimockGetUserByNameDone() &&
		m.MinimockSaveDone() &&
		m.MinimockUpdateDone()
}
