// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/go-park-mail-ru/2025_1_Quza/auth/internal/cache/redis.UserCacheInterface -o user_cache_interface_minimock.go -n UserCacheInterfaceMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/go-park-mail-ru/2025_1_Quza/auth/internal/model"
	"github.com/gojuno/minimock/v3"
)

// UserCacheInterfaceMock implements mm_redis.UserCacheInterface
type UserCacheInterfaceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, id int, user model.User) (err error)
	funcCreateOrigin    string
	inspectFuncCreate   func(ctx context.Context, id int, user model.User)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mUserCacheInterfaceMockCreate

	funcGetById          func(ctx context.Context, id int) (up1 *model.User, err error)
	funcGetByIdOrigin    string
	inspectFuncGetById   func(ctx context.Context, id int)
	afterGetByIdCounter  uint64
	beforeGetByIdCounter uint64
	GetByIdMock          mUserCacheInterfaceMockGetById

	funcGetByName          func(ctx context.Context, name string) (up1 *model.User, err error)
	funcGetByNameOrigin    string
	inspectFuncGetByName   func(ctx context.Context, name string)
	afterGetByNameCounter  uint64
	beforeGetByNameCounter uint64
	GetByNameMock          mUserCacheInterfaceMockGetByName
}

// NewUserCacheInterfaceMock returns a mock for mm_redis.UserCacheInterface
func NewUserCacheInterfaceMock(t minimock.Tester) *UserCacheInterfaceMock {
	m := &UserCacheInterfaceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mUserCacheInterfaceMockCreate{mock: m}
	m.CreateMock.callArgs = []*UserCacheInterfaceMockCreateParams{}

	m.GetByIdMock = mUserCacheInterfaceMockGetById{mock: m}
	m.GetByIdMock.callArgs = []*UserCacheInterfaceMockGetByIdParams{}

	m.GetByNameMock = mUserCacheInterfaceMockGetByName{mock: m}
	m.GetByNameMock.callArgs = []*UserCacheInterfaceMockGetByNameParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUserCacheInterfaceMockCreate struct {
	optional           bool
	mock               *UserCacheInterfaceMock
	defaultExpectation *UserCacheInterfaceMockCreateExpectation
	expectations       []*UserCacheInterfaceMockCreateExpectation

	callArgs []*UserCacheInterfaceMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserCacheInterfaceMockCreateExpectation specifies expectation struct of the UserCacheInterface.Create
type UserCacheInterfaceMockCreateExpectation struct {
	mock               *UserCacheInterfaceMock
	params             *UserCacheInterfaceMockCreateParams
	paramPtrs          *UserCacheInterfaceMockCreateParamPtrs
	expectationOrigins UserCacheInterfaceMockCreateExpectationOrigins
	results            *UserCacheInterfaceMockCreateResults
	returnOrigin       string
	Counter            uint64
}

// UserCacheInterfaceMockCreateParams contains parameters of the UserCacheInterface.Create
type UserCacheInterfaceMockCreateParams struct {
	ctx  context.Context
	id   int
	user model.User
}

// UserCacheInterfaceMockCreateParamPtrs contains pointers to parameters of the UserCacheInterface.Create
type UserCacheInterfaceMockCreateParamPtrs struct {
	ctx  *context.Context
	id   *int
	user *model.User
}

// UserCacheInterfaceMockCreateResults contains results of the UserCacheInterface.Create
type UserCacheInterfaceMockCreateResults struct {
	err error
}

// UserCacheInterfaceMockCreateOrigins contains origins of expectations of the UserCacheInterface.Create
type UserCacheInterfaceMockCreateExpectationOrigins struct {
	origin     string
	originCtx  string
	originId   string
	originUser string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mUserCacheInterfaceMockCreate) Optional() *mUserCacheInterfaceMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for UserCacheInterface.Create
func (mmCreate *mUserCacheInterfaceMockCreate) Expect(ctx context.Context, id int, user model.User) *mUserCacheInterfaceMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("UserCacheInterfaceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &UserCacheInterfaceMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("UserCacheInterfaceMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &UserCacheInterfaceMockCreateParams{ctx, id, user}
	mmCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for UserCacheInterface.Create
func (mmCreate *mUserCacheInterfaceMockCreate) ExpectCtxParam1(ctx context.Context) *mUserCacheInterfaceMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("UserCacheInterfaceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &UserCacheInterfaceMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("UserCacheInterfaceMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &UserCacheInterfaceMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectIdParam2 sets up expected param id for UserCacheInterface.Create
func (mmCreate *mUserCacheInterfaceMockCreate) ExpectIdParam2(id int) *mUserCacheInterfaceMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("UserCacheInterfaceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &UserCacheInterfaceMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("UserCacheInterfaceMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &UserCacheInterfaceMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.id = &id
	mmCreate.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectUserParam3 sets up expected param user for UserCacheInterface.Create
func (mmCreate *mUserCacheInterfaceMockCreate) ExpectUserParam3(user model.User) *mUserCacheInterfaceMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("UserCacheInterfaceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &UserCacheInterfaceMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("UserCacheInterfaceMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &UserCacheInterfaceMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.user = &user
	mmCreate.defaultExpectation.expectationOrigins.originUser = minimock.CallerInfo(1)

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the UserCacheInterface.Create
func (mmCreate *mUserCacheInterfaceMockCreate) Inspect(f func(ctx context.Context, id int, user model.User)) *mUserCacheInterfaceMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for UserCacheInterfaceMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by UserCacheInterface.Create
func (mmCreate *mUserCacheInterfaceMockCreate) Return(err error) *UserCacheInterfaceMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("UserCacheInterfaceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &UserCacheInterfaceMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &UserCacheInterfaceMockCreateResults{err}
	mmCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// Set uses given function f to mock the UserCacheInterface.Create method
func (mmCreate *mUserCacheInterfaceMockCreate) Set(f func(ctx context.Context, id int, user model.User) (err error)) *UserCacheInterfaceMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the UserCacheInterface.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the UserCacheInterface.Create method")
	}

	mmCreate.mock.funcCreate = f
	mmCreate.mock.funcCreateOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// When sets expectation for the UserCacheInterface.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mUserCacheInterfaceMockCreate) When(ctx context.Context, id int, user model.User) *UserCacheInterfaceMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("UserCacheInterfaceMock.Create mock is already set by Set")
	}

	expectation := &UserCacheInterfaceMockCreateExpectation{
		mock:               mmCreate.mock,
		params:             &UserCacheInterfaceMockCreateParams{ctx, id, user},
		expectationOrigins: UserCacheInterfaceMockCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up UserCacheInterface.Create return parameters for the expectation previously defined by the When method
func (e *UserCacheInterfaceMockCreateExpectation) Then(err error) *UserCacheInterfaceMock {
	e.results = &UserCacheInterfaceMockCreateResults{err}
	return e.mock
}

// Times sets number of times UserCacheInterface.Create should be invoked
func (mmCreate *mUserCacheInterfaceMockCreate) Times(n uint64) *mUserCacheInterfaceMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of UserCacheInterfaceMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	mmCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreate
}

func (mmCreate *mUserCacheInterfaceMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements mm_redis.UserCacheInterface
func (mmCreate *UserCacheInterfaceMock) Create(ctx context.Context, id int, user model.User) (err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	mmCreate.t.Helper()

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, id, user)
	}

	mm_params := UserCacheInterfaceMockCreateParams{ctx, id, user}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := UserCacheInterfaceMockCreateParams{ctx, id, user}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("UserCacheInterfaceMock.Create got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmCreate.t.Errorf("UserCacheInterfaceMock.Create got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

			if mm_want_ptrs.user != nil && !minimock.Equal(*mm_want_ptrs.user, mm_got.user) {
				mmCreate.t.Errorf("UserCacheInterfaceMock.Create got unexpected parameter user, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originUser, *mm_want_ptrs.user, mm_got.user, minimock.Diff(*mm_want_ptrs.user, mm_got.user))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("UserCacheInterfaceMock.Create got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreate.CreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the UserCacheInterfaceMock.Create")
		}
		return (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, id, user)
	}
	mmCreate.t.Fatalf("Unexpected call to UserCacheInterfaceMock.Create. %v %v %v", ctx, id, user)
	return
}

// CreateAfterCounter returns a count of finished UserCacheInterfaceMock.Create invocations
func (mmCreate *UserCacheInterfaceMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of UserCacheInterfaceMock.Create invocations
func (mmCreate *UserCacheInterfaceMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to UserCacheInterfaceMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mUserCacheInterfaceMockCreate) Calls() []*UserCacheInterfaceMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*UserCacheInterfaceMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *UserCacheInterfaceMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *UserCacheInterfaceMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserCacheInterfaceMock.Create at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserCacheInterfaceMock.Create at\n%s", m.CreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserCacheInterfaceMock.Create at\n%s with params: %#v", m.CreateMock.defaultExpectation.expectationOrigins.origin, *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Errorf("Expected call to UserCacheInterfaceMock.Create at\n%s", m.funcCreateOrigin)
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to UserCacheInterfaceMock.Create at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), m.CreateMock.expectedInvocationsOrigin, afterCreateCounter)
	}
}

type mUserCacheInterfaceMockGetById struct {
	optional           bool
	mock               *UserCacheInterfaceMock
	defaultExpectation *UserCacheInterfaceMockGetByIdExpectation
	expectations       []*UserCacheInterfaceMockGetByIdExpectation

	callArgs []*UserCacheInterfaceMockGetByIdParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserCacheInterfaceMockGetByIdExpectation specifies expectation struct of the UserCacheInterface.GetById
type UserCacheInterfaceMockGetByIdExpectation struct {
	mock               *UserCacheInterfaceMock
	params             *UserCacheInterfaceMockGetByIdParams
	paramPtrs          *UserCacheInterfaceMockGetByIdParamPtrs
	expectationOrigins UserCacheInterfaceMockGetByIdExpectationOrigins
	results            *UserCacheInterfaceMockGetByIdResults
	returnOrigin       string
	Counter            uint64
}

// UserCacheInterfaceMockGetByIdParams contains parameters of the UserCacheInterface.GetById
type UserCacheInterfaceMockGetByIdParams struct {
	ctx context.Context
	id  int
}

// UserCacheInterfaceMockGetByIdParamPtrs contains pointers to parameters of the UserCacheInterface.GetById
type UserCacheInterfaceMockGetByIdParamPtrs struct {
	ctx *context.Context
	id  *int
}

// UserCacheInterfaceMockGetByIdResults contains results of the UserCacheInterface.GetById
type UserCacheInterfaceMockGetByIdResults struct {
	up1 *model.User
	err error
}

// UserCacheInterfaceMockGetByIdOrigins contains origins of expectations of the UserCacheInterface.GetById
type UserCacheInterfaceMockGetByIdExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetById *mUserCacheInterfaceMockGetById) Optional() *mUserCacheInterfaceMockGetById {
	mmGetById.optional = true
	return mmGetById
}

// Expect sets up expected params for UserCacheInterface.GetById
func (mmGetById *mUserCacheInterfaceMockGetById) Expect(ctx context.Context, id int) *mUserCacheInterfaceMockGetById {
	if mmGetById.mock.funcGetById != nil {
		mmGetById.mock.t.Fatalf("UserCacheInterfaceMock.GetById mock is already set by Set")
	}

	if mmGetById.defaultExpectation == nil {
		mmGetById.defaultExpectation = &UserCacheInterfaceMockGetByIdExpectation{}
	}

	if mmGetById.defaultExpectation.paramPtrs != nil {
		mmGetById.mock.t.Fatalf("UserCacheInterfaceMock.GetById mock is already set by ExpectParams functions")
	}

	mmGetById.defaultExpectation.params = &UserCacheInterfaceMockGetByIdParams{ctx, id}
	mmGetById.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetById.expectations {
		if minimock.Equal(e.params, mmGetById.defaultExpectation.params) {
			mmGetById.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetById.defaultExpectation.params)
		}
	}

	return mmGetById
}

// ExpectCtxParam1 sets up expected param ctx for UserCacheInterface.GetById
func (mmGetById *mUserCacheInterfaceMockGetById) ExpectCtxParam1(ctx context.Context) *mUserCacheInterfaceMockGetById {
	if mmGetById.mock.funcGetById != nil {
		mmGetById.mock.t.Fatalf("UserCacheInterfaceMock.GetById mock is already set by Set")
	}

	if mmGetById.defaultExpectation == nil {
		mmGetById.defaultExpectation = &UserCacheInterfaceMockGetByIdExpectation{}
	}

	if mmGetById.defaultExpectation.params != nil {
		mmGetById.mock.t.Fatalf("UserCacheInterfaceMock.GetById mock is already set by Expect")
	}

	if mmGetById.defaultExpectation.paramPtrs == nil {
		mmGetById.defaultExpectation.paramPtrs = &UserCacheInterfaceMockGetByIdParamPtrs{}
	}
	mmGetById.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetById.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetById
}

// ExpectIdParam2 sets up expected param id for UserCacheInterface.GetById
func (mmGetById *mUserCacheInterfaceMockGetById) ExpectIdParam2(id int) *mUserCacheInterfaceMockGetById {
	if mmGetById.mock.funcGetById != nil {
		mmGetById.mock.t.Fatalf("UserCacheInterfaceMock.GetById mock is already set by Set")
	}

	if mmGetById.defaultExpectation == nil {
		mmGetById.defaultExpectation = &UserCacheInterfaceMockGetByIdExpectation{}
	}

	if mmGetById.defaultExpectation.params != nil {
		mmGetById.mock.t.Fatalf("UserCacheInterfaceMock.GetById mock is already set by Expect")
	}

	if mmGetById.defaultExpectation.paramPtrs == nil {
		mmGetById.defaultExpectation.paramPtrs = &UserCacheInterfaceMockGetByIdParamPtrs{}
	}
	mmGetById.defaultExpectation.paramPtrs.id = &id
	mmGetById.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmGetById
}

// Inspect accepts an inspector function that has same arguments as the UserCacheInterface.GetById
func (mmGetById *mUserCacheInterfaceMockGetById) Inspect(f func(ctx context.Context, id int)) *mUserCacheInterfaceMockGetById {
	if mmGetById.mock.inspectFuncGetById != nil {
		mmGetById.mock.t.Fatalf("Inspect function is already set for UserCacheInterfaceMock.GetById")
	}

	mmGetById.mock.inspectFuncGetById = f

	return mmGetById
}

// Return sets up results that will be returned by UserCacheInterface.GetById
func (mmGetById *mUserCacheInterfaceMockGetById) Return(up1 *model.User, err error) *UserCacheInterfaceMock {
	if mmGetById.mock.funcGetById != nil {
		mmGetById.mock.t.Fatalf("UserCacheInterfaceMock.GetById mock is already set by Set")
	}

	if mmGetById.defaultExpectation == nil {
		mmGetById.defaultExpectation = &UserCacheInterfaceMockGetByIdExpectation{mock: mmGetById.mock}
	}
	mmGetById.defaultExpectation.results = &UserCacheInterfaceMockGetByIdResults{up1, err}
	mmGetById.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetById.mock
}

// Set uses given function f to mock the UserCacheInterface.GetById method
func (mmGetById *mUserCacheInterfaceMockGetById) Set(f func(ctx context.Context, id int) (up1 *model.User, err error)) *UserCacheInterfaceMock {
	if mmGetById.defaultExpectation != nil {
		mmGetById.mock.t.Fatalf("Default expectation is already set for the UserCacheInterface.GetById method")
	}

	if len(mmGetById.expectations) > 0 {
		mmGetById.mock.t.Fatalf("Some expectations are already set for the UserCacheInterface.GetById method")
	}

	mmGetById.mock.funcGetById = f
	mmGetById.mock.funcGetByIdOrigin = minimock.CallerInfo(1)
	return mmGetById.mock
}

// When sets expectation for the UserCacheInterface.GetById which will trigger the result defined by the following
// Then helper
func (mmGetById *mUserCacheInterfaceMockGetById) When(ctx context.Context, id int) *UserCacheInterfaceMockGetByIdExpectation {
	if mmGetById.mock.funcGetById != nil {
		mmGetById.mock.t.Fatalf("UserCacheInterfaceMock.GetById mock is already set by Set")
	}

	expectation := &UserCacheInterfaceMockGetByIdExpectation{
		mock:               mmGetById.mock,
		params:             &UserCacheInterfaceMockGetByIdParams{ctx, id},
		expectationOrigins: UserCacheInterfaceMockGetByIdExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetById.expectations = append(mmGetById.expectations, expectation)
	return expectation
}

// Then sets up UserCacheInterface.GetById return parameters for the expectation previously defined by the When method
func (e *UserCacheInterfaceMockGetByIdExpectation) Then(up1 *model.User, err error) *UserCacheInterfaceMock {
	e.results = &UserCacheInterfaceMockGetByIdResults{up1, err}
	return e.mock
}

// Times sets number of times UserCacheInterface.GetById should be invoked
func (mmGetById *mUserCacheInterfaceMockGetById) Times(n uint64) *mUserCacheInterfaceMockGetById {
	if n == 0 {
		mmGetById.mock.t.Fatalf("Times of UserCacheInterfaceMock.GetById mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetById.expectedInvocations, n)
	mmGetById.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetById
}

func (mmGetById *mUserCacheInterfaceMockGetById) invocationsDone() bool {
	if len(mmGetById.expectations) == 0 && mmGetById.defaultExpectation == nil && mmGetById.mock.funcGetById == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetById.mock.afterGetByIdCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetById.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetById implements mm_redis.UserCacheInterface
func (mmGetById *UserCacheInterfaceMock) GetById(ctx context.Context, id int) (up1 *model.User, err error) {
	mm_atomic.AddUint64(&mmGetById.beforeGetByIdCounter, 1)
	defer mm_atomic.AddUint64(&mmGetById.afterGetByIdCounter, 1)

	mmGetById.t.Helper()

	if mmGetById.inspectFuncGetById != nil {
		mmGetById.inspectFuncGetById(ctx, id)
	}

	mm_params := UserCacheInterfaceMockGetByIdParams{ctx, id}

	// Record call args
	mmGetById.GetByIdMock.mutex.Lock()
	mmGetById.GetByIdMock.callArgs = append(mmGetById.GetByIdMock.callArgs, &mm_params)
	mmGetById.GetByIdMock.mutex.Unlock()

	for _, e := range mmGetById.GetByIdMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmGetById.GetByIdMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetById.GetByIdMock.defaultExpectation.Counter, 1)
		mm_want := mmGetById.GetByIdMock.defaultExpectation.params
		mm_want_ptrs := mmGetById.GetByIdMock.defaultExpectation.paramPtrs

		mm_got := UserCacheInterfaceMockGetByIdParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetById.t.Errorf("UserCacheInterfaceMock.GetById got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetById.GetByIdMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmGetById.t.Errorf("UserCacheInterfaceMock.GetById got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetById.GetByIdMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetById.t.Errorf("UserCacheInterfaceMock.GetById got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetById.GetByIdMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetById.GetByIdMock.defaultExpectation.results
		if mm_results == nil {
			mmGetById.t.Fatal("No results are set for the UserCacheInterfaceMock.GetById")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmGetById.funcGetById != nil {
		return mmGetById.funcGetById(ctx, id)
	}
	mmGetById.t.Fatalf("Unexpected call to UserCacheInterfaceMock.GetById. %v %v", ctx, id)
	return
}

// GetByIdAfterCounter returns a count of finished UserCacheInterfaceMock.GetById invocations
func (mmGetById *UserCacheInterfaceMock) GetByIdAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetById.afterGetByIdCounter)
}

// GetByIdBeforeCounter returns a count of UserCacheInterfaceMock.GetById invocations
func (mmGetById *UserCacheInterfaceMock) GetByIdBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetById.beforeGetByIdCounter)
}

// Calls returns a list of arguments used in each call to UserCacheInterfaceMock.GetById.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetById *mUserCacheInterfaceMockGetById) Calls() []*UserCacheInterfaceMockGetByIdParams {
	mmGetById.mutex.RLock()

	argCopy := make([]*UserCacheInterfaceMockGetByIdParams, len(mmGetById.callArgs))
	copy(argCopy, mmGetById.callArgs)

	mmGetById.mutex.RUnlock()

	return argCopy
}

// MinimockGetByIdDone returns true if the count of the GetById invocations corresponds
// the number of defined expectations
func (m *UserCacheInterfaceMock) MinimockGetByIdDone() bool {
	if m.GetByIdMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByIdMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByIdMock.invocationsDone()
}

// MinimockGetByIdInspect logs each unmet expectation
func (m *UserCacheInterfaceMock) MinimockGetByIdInspect() {
	for _, e := range m.GetByIdMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserCacheInterfaceMock.GetById at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByIdCounter := mm_atomic.LoadUint64(&m.afterGetByIdCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByIdMock.defaultExpectation != nil && afterGetByIdCounter < 1 {
		if m.GetByIdMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserCacheInterfaceMock.GetById at\n%s", m.GetByIdMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserCacheInterfaceMock.GetById at\n%s with params: %#v", m.GetByIdMock.defaultExpectation.expectationOrigins.origin, *m.GetByIdMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetById != nil && afterGetByIdCounter < 1 {
		m.t.Errorf("Expected call to UserCacheInterfaceMock.GetById at\n%s", m.funcGetByIdOrigin)
	}

	if !m.GetByIdMock.invocationsDone() && afterGetByIdCounter > 0 {
		m.t.Errorf("Expected %d calls to UserCacheInterfaceMock.GetById at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByIdMock.expectedInvocations), m.GetByIdMock.expectedInvocationsOrigin, afterGetByIdCounter)
	}
}

type mUserCacheInterfaceMockGetByName struct {
	optional           bool
	mock               *UserCacheInterfaceMock
	defaultExpectation *UserCacheInterfaceMockGetByNameExpectation
	expectations       []*UserCacheInterfaceMockGetByNameExpectation

	callArgs []*UserCacheInterfaceMockGetByNameParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserCacheInterfaceMockGetByNameExpectation specifies expectation struct of the UserCacheInterface.GetByName
type UserCacheInterfaceMockGetByNameExpectation struct {
	mock               *UserCacheInterfaceMock
	params             *UserCacheInterfaceMockGetByNameParams
	paramPtrs          *UserCacheInterfaceMockGetByNameParamPtrs
	expectationOrigins UserCacheInterfaceMockGetByNameExpectationOrigins
	results            *UserCacheInterfaceMockGetByNameResults
	returnOrigin       string
	Counter            uint64
}

// UserCacheInterfaceMockGetByNameParams contains parameters of the UserCacheInterface.GetByName
type UserCacheInterfaceMockGetByNameParams struct {
	ctx  context.Context
	name string
}

// UserCacheInterfaceMockGetByNameParamPtrs contains pointers to parameters of the UserCacheInterface.GetByName
type UserCacheInterfaceMockGetByNameParamPtrs struct {
	ctx  *context.Context
	name *string
}

// UserCacheInterfaceMockGetByNameResults contains results of the UserCacheInterface.GetByName
type UserCacheInterfaceMockGetByNameResults struct {
	up1 *model.User
	err error
}

// UserCacheInterfaceMockGetByNameOrigins contains origins of expectations of the UserCacheInterface.GetByName
type UserCacheInterfaceMockGetByNameExpectationOrigins struct {
	origin     string
	originCtx  string
	originName string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetByName *mUserCacheInterfaceMockGetByName) Optional() *mUserCacheInterfaceMockGetByName {
	mmGetByName.optional = true
	return mmGetByName
}

// Expect sets up expected params for UserCacheInterface.GetByName
func (mmGetByName *mUserCacheInterfaceMockGetByName) Expect(ctx context.Context, name string) *mUserCacheInterfaceMockGetByName {
	if mmGetByName.mock.funcGetByName != nil {
		mmGetByName.mock.t.Fatalf("UserCacheInterfaceMock.GetByName mock is already set by Set")
	}

	if mmGetByName.defaultExpectation == nil {
		mmGetByName.defaultExpectation = &UserCacheInterfaceMockGetByNameExpectation{}
	}

	if mmGetByName.defaultExpectation.paramPtrs != nil {
		mmGetByName.mock.t.Fatalf("UserCacheInterfaceMock.GetByName mock is already set by ExpectParams functions")
	}

	mmGetByName.defaultExpectation.params = &UserCacheInterfaceMockGetByNameParams{ctx, name}
	mmGetByName.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetByName.expectations {
		if minimock.Equal(e.params, mmGetByName.defaultExpectation.params) {
			mmGetByName.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetByName.defaultExpectation.params)
		}
	}

	return mmGetByName
}

// ExpectCtxParam1 sets up expected param ctx for UserCacheInterface.GetByName
func (mmGetByName *mUserCacheInterfaceMockGetByName) ExpectCtxParam1(ctx context.Context) *mUserCacheInterfaceMockGetByName {
	if mmGetByName.mock.funcGetByName != nil {
		mmGetByName.mock.t.Fatalf("UserCacheInterfaceMock.GetByName mock is already set by Set")
	}

	if mmGetByName.defaultExpectation == nil {
		mmGetByName.defaultExpectation = &UserCacheInterfaceMockGetByNameExpectation{}
	}

	if mmGetByName.defaultExpectation.params != nil {
		mmGetByName.mock.t.Fatalf("UserCacheInterfaceMock.GetByName mock is already set by Expect")
	}

	if mmGetByName.defaultExpectation.paramPtrs == nil {
		mmGetByName.defaultExpectation.paramPtrs = &UserCacheInterfaceMockGetByNameParamPtrs{}
	}
	mmGetByName.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetByName.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetByName
}

// ExpectNameParam2 sets up expected param name for UserCacheInterface.GetByName
func (mmGetByName *mUserCacheInterfaceMockGetByName) ExpectNameParam2(name string) *mUserCacheInterfaceMockGetByName {
	if mmGetByName.mock.funcGetByName != nil {
		mmGetByName.mock.t.Fatalf("UserCacheInterfaceMock.GetByName mock is already set by Set")
	}

	if mmGetByName.defaultExpectation == nil {
		mmGetByName.defaultExpectation = &UserCacheInterfaceMockGetByNameExpectation{}
	}

	if mmGetByName.defaultExpectation.params != nil {
		mmGetByName.mock.t.Fatalf("UserCacheInterfaceMock.GetByName mock is already set by Expect")
	}

	if mmGetByName.defaultExpectation.paramPtrs == nil {
		mmGetByName.defaultExpectation.paramPtrs = &UserCacheInterfaceMockGetByNameParamPtrs{}
	}
	mmGetByName.defaultExpectation.paramPtrs.name = &name
	mmGetByName.defaultExpectation.expectationOrigins.originName = minimock.CallerInfo(1)

	return mmGetByName
}

// Inspect accepts an inspector function that has same arguments as the UserCacheInterface.GetByName
func (mmGetByName *mUserCacheInterfaceMockGetByName) Inspect(f func(ctx context.Context, name string)) *mUserCacheInterfaceMockGetByName {
	if mmGetByName.mock.inspectFuncGetByName != nil {
		mmGetByName.mock.t.Fatalf("Inspect function is already set for UserCacheInterfaceMock.GetByName")
	}

	mmGetByName.mock.inspectFuncGetByName = f

	return mmGetByName
}

// Return sets up results that will be returned by UserCacheInterface.GetByName
func (mmGetByName *mUserCacheInterfaceMockGetByName) Return(up1 *model.User, err error) *UserCacheInterfaceMock {
	if mmGetByName.mock.funcGetByName != nil {
		mmGetByName.mock.t.Fatalf("UserCacheInterfaceMock.GetByName mock is already set by Set")
	}

	if mmGetByName.defaultExpectation == nil {
		mmGetByName.defaultExpectation = &UserCacheInterfaceMockGetByNameExpectation{mock: mmGetByName.mock}
	}
	mmGetByName.defaultExpectation.results = &UserCacheInterfaceMockGetByNameResults{up1, err}
	mmGetByName.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetByName.mock
}

// Set uses given function f to mock the UserCacheInterface.GetByName method
func (mmGetByName *mUserCacheInterfaceMockGetByName) Set(f func(ctx context.Context, name string) (up1 *model.User, err error)) *UserCacheInterfaceMock {
	if mmGetByName.defaultExpectation != nil {
		mmGetByName.mock.t.Fatalf("Default expectation is already set for the UserCacheInterface.GetByName method")
	}

	if len(mmGetByName.expectations) > 0 {
		mmGetByName.mock.t.Fatalf("Some expectations are already set for the UserCacheInterface.GetByName method")
	}

	mmGetByName.mock.funcGetByName = f
	mmGetByName.mock.funcGetByNameOrigin = minimock.CallerInfo(1)
	return mmGetByName.mock
}

// When sets expectation for the UserCacheInterface.GetByName which will trigger the result defined by the following
// Then helper
func (mmGetByName *mUserCacheInterfaceMockGetByName) When(ctx context.Context, name string) *UserCacheInterfaceMockGetByNameExpectation {
	if mmGetByName.mock.funcGetByName != nil {
		mmGetByName.mock.t.Fatalf("UserCacheInterfaceMock.GetByName mock is already set by Set")
	}

	expectation := &UserCacheInterfaceMockGetByNameExpectation{
		mock:               mmGetByName.mock,
		params:             &UserCacheInterfaceMockGetByNameParams{ctx, name},
		expectationOrigins: UserCacheInterfaceMockGetByNameExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetByName.expectations = append(mmGetByName.expectations, expectation)
	return expectation
}

// Then sets up UserCacheInterface.GetByName return parameters for the expectation previously defined by the When method
func (e *UserCacheInterfaceMockGetByNameExpectation) Then(up1 *model.User, err error) *UserCacheInterfaceMock {
	e.results = &UserCacheInterfaceMockGetByNameResults{up1, err}
	return e.mock
}

// Times sets number of times UserCacheInterface.GetByName should be invoked
func (mmGetByName *mUserCacheInterfaceMockGetByName) Times(n uint64) *mUserCacheInterfaceMockGetByName {
	if n == 0 {
		mmGetByName.mock.t.Fatalf("Times of UserCacheInterfaceMock.GetByName mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetByName.expectedInvocations, n)
	mmGetByName.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetByName
}

func (mmGetByName *mUserCacheInterfaceMockGetByName) invocationsDone() bool {
	if len(mmGetByName.expectations) == 0 && mmGetByName.defaultExpectation == nil && mmGetByName.mock.funcGetByName == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetByName.mock.afterGetByNameCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetByName.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetByName implements mm_redis.UserCacheInterface
func (mmGetByName *UserCacheInterfaceMock) GetByName(ctx context.Context, name string) (up1 *model.User, err error) {
	mm_atomic.AddUint64(&mmGetByName.beforeGetByNameCounter, 1)
	defer mm_atomic.AddUint64(&mmGetByName.afterGetByNameCounter, 1)

	mmGetByName.t.Helper()

	if mmGetByName.inspectFuncGetByName != nil {
		mmGetByName.inspectFuncGetByName(ctx, name)
	}

	mm_params := UserCacheInterfaceMockGetByNameParams{ctx, name}

	// Record call args
	mmGetByName.GetByNameMock.mutex.Lock()
	mmGetByName.GetByNameMock.callArgs = append(mmGetByName.GetByNameMock.callArgs, &mm_params)
	mmGetByName.GetByNameMock.mutex.Unlock()

	for _, e := range mmGetByName.GetByNameMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmGetByName.GetByNameMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetByName.GetByNameMock.defaultExpectation.Counter, 1)
		mm_want := mmGetByName.GetByNameMock.defaultExpectation.params
		mm_want_ptrs := mmGetByName.GetByNameMock.defaultExpectation.paramPtrs

		mm_got := UserCacheInterfaceMockGetByNameParams{ctx, name}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetByName.t.Errorf("UserCacheInterfaceMock.GetByName got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByName.GetByNameMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.name != nil && !minimock.Equal(*mm_want_ptrs.name, mm_got.name) {
				mmGetByName.t.Errorf("UserCacheInterfaceMock.GetByName got unexpected parameter name, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByName.GetByNameMock.defaultExpectation.expectationOrigins.originName, *mm_want_ptrs.name, mm_got.name, minimock.Diff(*mm_want_ptrs.name, mm_got.name))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetByName.t.Errorf("UserCacheInterfaceMock.GetByName got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetByName.GetByNameMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetByName.GetByNameMock.defaultExpectation.results
		if mm_results == nil {
			mmGetByName.t.Fatal("No results are set for the UserCacheInterfaceMock.GetByName")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmGetByName.funcGetByName != nil {
		return mmGetByName.funcGetByName(ctx, name)
	}
	mmGetByName.t.Fatalf("Unexpected call to UserCacheInterfaceMock.GetByName. %v %v", ctx, name)
	return
}

// GetByNameAfterCounter returns a count of finished UserCacheInterfaceMock.GetByName invocations
func (mmGetByName *UserCacheInterfaceMock) GetByNameAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByName.afterGetByNameCounter)
}

// GetByNameBeforeCounter returns a count of UserCacheInterfaceMock.GetByName invocations
func (mmGetByName *UserCacheInterfaceMock) GetByNameBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByName.beforeGetByNameCounter)
}

// Calls returns a list of arguments used in each call to UserCacheInterfaceMock.GetByName.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetByName *mUserCacheInterfaceMockGetByName) Calls() []*UserCacheInterfaceMockGetByNameParams {
	mmGetByName.mutex.RLock()

	argCopy := make([]*UserCacheInterfaceMockGetByNameParams, len(mmGetByName.callArgs))
	copy(argCopy, mmGetByName.callArgs)

	mmGetByName.mutex.RUnlock()

	return argCopy
}

// MinimockGetByNameDone returns true if the count of the GetByName invocations corresponds
// the number of defined expectations
func (m *UserCacheInterfaceMock) MinimockGetByNameDone() bool {
	if m.GetByNameMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByNameMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByNameMock.invocationsDone()
}

// MinimockGetByNameInspect logs each unmet expectation
func (m *UserCacheInterfaceMock) MinimockGetByNameInspect() {
	for _, e := range m.GetByNameMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserCacheInterfaceMock.GetByName at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByNameCounter := mm_atomic.LoadUint64(&m.afterGetByNameCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByNameMock.defaultExpectation != nil && afterGetByNameCounter < 1 {
		if m.GetByNameMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserCacheInterfaceMock.GetByName at\n%s", m.GetByNameMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserCacheInterfaceMock.GetByName at\n%s with params: %#v", m.GetByNameMock.defaultExpectation.expectationOrigins.origin, *m.GetByNameMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetByName != nil && afterGetByNameCounter < 1 {
		m.t.Errorf("Expected call to UserCacheInterfaceMock.GetByName at\n%s", m.funcGetByNameOrigin)
	}

	if !m.GetByNameMock.invocationsDone() && afterGetByNameCounter > 0 {
		m.t.Errorf("Expected %d calls to UserCacheInterfaceMock.GetByName at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByNameMock.expectedInvocations), m.GetByNameMock.expectedInvocationsOrigin, afterGetByNameCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UserCacheInterfaceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()

			m.MinimockGetByIdInspect()

			m.MinimockGetByNameInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UserCacheInterfaceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UserCacheInterfaceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone() &&
		m.MinimockGetByIdDone() &&
		m.MinimockGetByNameDone()
}
